/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export enum PublicCompletionBatchRequestStatus {
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
}

export enum PublicCompletionBatchRequestType {
  ASYNC = 'ASYNC',
  CALLBACK = 'CALLBACK',
  SYNC = 'SYNC',
}

export enum PublicModelPricingSource {
  SYSTEM = 'SYSTEM',
  USER = 'USER',
}

export enum PublicProviderType {
  LOCAL = 'LOCAL',
  OIDC = 'OIDC',
}

export enum PublicRequestAuditType {
  COMPLETION = 'COMPLETION',
  COMPLETION_BATCH = 'COMPLETION_BATCH',
  RESPONSES = 'RESPONSES',
}

export enum PublicUserState {
  ACTIVE = 'ACTIVE',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  INACTIVE = 'INACTIVE',
}

export enum PublicWorkspaceUserRole {
  MEMBER = 'MEMBER',
  OWNER = 'OWNER',
}

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AiConnection {
  allowedModels: ColumnType<string[] | null, string | null, string | null>;
  capacity: ColumnType<any[] | null, string | null, string | null>;
  config: ColumnType<any | null, string | null, string | null>;
  connectionId: Generated<string>;
  createdAt: Generated<Timestamp>;
  createdBy: string;
  description: string | null;
  discoveredCapacity: ColumnType<any | null, string | null, string | null>;
  environmentId: string;
  name: string;
  provider: string;
  updatedAt: Generated<Timestamp>;
  updatedBy: string;
  workspaceId: string;
}

export interface AiResource {
  capacity: ColumnType<any[] | null, string | null, string | null>;
  createdAt: Generated<Timestamp>;
  createdBy: string;
  defaultArgs: Json | null;
  description: string | null;
  enforceCapacity: Generated<boolean>;
  environmentId: string;
  fallbackModels: ColumnType<any[] | null, string | null, string | null>;
  model: ColumnType<any, string, string | null>;
  name: string;
  resourceId: Generated<string>;
  routing: ColumnType<any | null, string | null, string | null>;
  secondaryModels: ColumnType<any[] | null, string | null, string | null>;
  updatedAt: Generated<Timestamp>;
  updatedBy: string;
  useFallback: Generated<boolean>;
  workspaceId: string;
}

export interface ApiKey {
  apiKeyId: Generated<string>;
  capacity: ColumnType<any[] | null, string | null, string | null>;
  createdAt: Generated<Timestamp>;
  createdBy: string;
  description: string | null;
  enabled: Generated<boolean>;
  enforceCapacity: Generated<boolean>;
  environmentId: string;
  hash: string;
  labels: ColumnType<any[] | null, string | null, string | null>;
  maskedKey: string;
  name: string;
  resources: ColumnType<any[], string, string | null>;
  updatedAt: Generated<Timestamp>;
  updatedBy: string;
  workspaceId: string;
}

export interface CompletionBatch {
  batchId: Generated<string>;
  callbackOptions: ColumnType<any | null, string | null, string | null>;
  capacity: ColumnType<any[] | null, string | null, string | null>;
  completed: Generated<number>;
  completedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  createdByApiKeyId: string | null;
  createdByUserId: string | null;
  environmentId: string;
  errorMessage: string | null;
  failed: Generated<number>;
  pending: Generated<number>;
  running: Generated<number>;
  status: PublicCompletionBatchRequestStatus;
  timestamp: Timestamp;
  totalEstimatedPromptTokens: Generated<number>;
  totalItems: Generated<number>;
  totalOutputTokens: Generated<number>;
  totalPromptTokens: Generated<number>;
  type: PublicCompletionBatchRequestType;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface CompletionBatchItem {
  batchId: string;
  completedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  environmentId: string;
  errorMessage: string | null;
  estimatedPromptTokens: Generated<number>;
  itemId: Generated<string>;
  outputTokens: Generated<number>;
  promptTokens: Generated<number>;
  request: ColumnType<any | null, string | null, string | null>;
  resourceId: string;
  response: ColumnType<any | null, string | null, string | null>;
  retryCount: Generated<number>;
  status: PublicCompletionBatchRequestStatus;
  totalTokens: Generated<number>;
  workspaceId: string;
}

export interface Environment {
  createdAt: Generated<Timestamp>;
  createdBy: string;
  description: string | null;
  environmentId: Generated<string>;
  name: string;
  updatedAt: Generated<Timestamp>;
  updatedBy: string;
  workspaceId: string;
}

export interface GlobalSecret {
  createdAt: Generated<Timestamp>;
  description: string | null;
  name: string;
  secretId: Generated<string>;
  value: string;
}

export interface ModelPricing {
  cachedInputCostPerToken: Generated<number | null>;
  createdAt: Generated<Timestamp>;
  createdBy: string;
  inputCostPerToken: number;
  model: string;
  outputCostPerToken: number;
  pricingId: Generated<string>;
  provider: string;
  reasoningCostPerToken: Generated<number | null>;
  source: Generated<PublicModelPricingSource>;
  updatedAt: Generated<Timestamp>;
  updatedBy: string;
}

export interface OidcProvider {
  consumed: Generated<boolean>;
  expiresAt: Timestamp | null;
  grantId: string | null;
  id: string;
  payload: Json;
  uid: string | null;
  userCode: string | null;
}

export interface PoolDefinition {
  createdAt: Generated<Timestamp>;
  createdBy: string;
  definition: ColumnType<any[], string, string | null>;
  environmentId: string;
  updatedAt: Generated<Timestamp>;
  updatedBy: string;
  workspaceId: string;
}

export interface RequestAudit {
  acceptedPredictionTokens: number | null;
  apiKeyId: string | null;
  audioTokens: number | null;
  batchId: string | null;
  cacheCreationEphemeral1hTokens: number | null;
  cacheCreationEphemeral5mTokens: number | null;
  cacheCreationInputTokens: number | null;
  cachedTokens: number | null;
  connectionId: string | null;
  correlationId: string | null;
  cost: Json | null;
  duration: number;
  environmentId: string;
  errorCount: Generated<number | null>;
  errorMessage: string | null;
  events: Json | null;
  failureReason: string | null;
  format: string | null;
  gateDuration: number | null;
  id: Generated<string>;
  messageId: string | null;
  metadata: Json | null;
  model: string | null;
  outputTokens: number | null;
  promptTokens: number | null;
  provider: string | null;
  providerDuration: number | null;
  providerRequestPayload: Json | null;
  reasoningTokens: number | null;
  rejectedPredictionTokens: number | null;
  requestDuration: number | null;
  requestId: string;
  requestPayload: Json | null;
  resourceId: string | null;
  responseData: Json | null;
  responseHeaders: Json | null;
  routingDuration: number | null;
  serverToolUseCodeExecutionRequests: number | null;
  serverToolUseWebSearchRequests: number | null;
  serviceTier: string | null;
  sourceIp: string | null;
  statusCode: number;
  successCount: Generated<number | null>;
  systemFingerprint: string | null;
  timestamp: Timestamp;
  timeToFirstToken: number | null;
  tokensPerSecond: number | null;
  totalTokens: number | null;
  type: PublicRequestAuditType;
  userId: string | null;
  workspaceId: string;
}

export interface RequestAuditMetadatum {
  auditId: string;
  cachedTokens: number | null;
  connectionId: string | null;
  environmentId: string;
  errorCount: Generated<number | null>;
  key: string;
  model: string | null;
  outputTokens: number | null;
  promptTokens: number | null;
  provider: string | null;
  reasoningTokens: number | null;
  requestDuration: number | null;
  resourceId: string | null;
  successCount: Generated<number | null>;
  timestamp: Timestamp;
  totalCost: number | null;
  totalTokens: number | null;
  value: string;
  workspaceId: string;
}

export interface Role {
  createdAt: Generated<Timestamp>;
  createdBy: string;
  description: string | null;
  name: string;
  policy: ColumnType<any | null, string | null, string | null>;
  roleId: Generated<string>;
  updatedAt: Generated<Timestamp>;
  updatedBy: string;
}

export interface UserRole {
  assignedAt: Generated<Timestamp>;
  assignedBy: string;
  roleId: string;
  userId: string;
}

export interface User {
  createdAt: Generated<Timestamp>;
  createdBy: string | null;
  email: string;
  emailVerified: Generated<boolean>;
  firstName: string;
  id: Generated<string>;
  lastName: string;
  name: string;
  passwordHash: string | null;
  pictureUrl: string | null;
  providerId: string;
  providerMetadata: Json | null;
  providerType: PublicProviderType;
  state: PublicUserState;
  updatedAt: Generated<Timestamp>;
  updatedBy: string | null;
  username: string;
}

export interface Workspace {
  createdAt: Generated<Timestamp>;
  createdBy: string;
  description: string | null;
  name: string;
  updatedAt: Generated<Timestamp>;
  updatedBy: string;
  workspaceId: Generated<string>;
}

export interface WorkspaceUser {
  addedAt: Generated<Timestamp>;
  addedBy: string;
  role: PublicWorkspaceUserRole;
  userId: string;
  workspaceId: string;
}

export interface DB {
  aiConnections: AiConnection;
  aiResources: AiResource;
  apiKeys: ApiKey;
  completionBatch: CompletionBatch;
  completionBatchItems: CompletionBatchItem;
  environments: Environment;
  globalSecrets: GlobalSecret;
  modelPricing: ModelPricing;
  oidcProvider: OidcProvider;
  poolDefinitions: PoolDefinition;
  requestAudit: RequestAudit;
  requestAuditMetadata: RequestAuditMetadatum;
  roles: Role;
  userRoles: UserRole;
  users: User;
  workspaces: Workspace;
  workspaceUsers: WorkspaceUser;
}
