// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type Options as Options2,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from './client';
import { client } from './client.gen';
import type {
  AssignUsersToRoleData,
  AssignUsersToRoleErrors,
  AssignUsersToRoleResponses,
  AssignUsersToWorkspaceData,
  AssignUsersToWorkspaceErrors,
  AssignUsersToWorkspaceResponses,
  CancelCompletionBatchData,
  CancelCompletionBatchErrors,
  CancelCompletionBatchResponses,
  CompletionData,
  CompletionResponses,
  CreateAiConnectionData,
  CreateAiConnectionErrors,
  CreateAiConnectionResponses,
  CreateAiResourceData,
  CreateAiResourceErrors,
  CreateAiResourceResponses,
  CreateApiKeyData,
  CreateApiKeyErrors,
  CreateApiKeyResponses,
  CreateCompletionBatchData,
  CreateCompletionBatchErrors,
  CreateCompletionBatchResponses,
  CreateEnvironmentData,
  CreateEnvironmentErrors,
  CreateEnvironmentResponses,
  CreateRoleData,
  CreateRoleErrors,
  CreateRoleResponses,
  CreateUserData,
  CreateUserErrors,
  CreateUserResponses,
  CreateWorkspaceData,
  CreateWorkspaceErrors,
  CreateWorkspaceResponses,
  DeleteAiConnectionData,
  DeleteAiConnectionErrors,
  DeleteAiConnectionResponses,
  DeleteAiResourceData,
  DeleteAiResourceErrors,
  DeleteAiResourceResponses,
  DeleteApiKeyData,
  DeleteApiKeyErrors,
  DeleteApiKeyResponses,
  DeleteEnvironmentData,
  DeleteEnvironmentErrors,
  DeleteEnvironmentResponses,
  DeletePoolDefinitionData,
  DeletePoolDefinitionErrors,
  DeletePoolDefinitionResponses,
  DeleteRoleData,
  DeleteRoleErrors,
  DeleteRoleResponses,
  DeleteUserData,
  DeleteUserErrors,
  DeleteUserResponses,
  DeleteWorkspaceData,
  DeleteWorkspaceErrors,
  DeleteWorkspaceResponses,
  GetAiConnectionByIdData,
  GetAiConnectionByIdErrors,
  GetAiConnectionByIdResponses,
  GetAiConnectionsData,
  GetAiConnectionsErrors,
  GetAiConnectionsResponses,
  GetAiProvidersData,
  GetAiProvidersErrors,
  GetAiProvidersResponses,
  GetAiResourceByIdData,
  GetAiResourceByIdErrors,
  GetAiResourceByIdResponses,
  GetAiResourcesData,
  GetAiResourcesErrors,
  GetAiResourcesResponses,
  GetApiKeyByIdData,
  GetApiKeyByIdErrors,
  GetApiKeyByIdResponses,
  GetApiKeysData,
  GetApiKeysErrors,
  GetApiKeysResponses,
  GetCompletionAuditData,
  GetCompletionAuditErrors,
  GetCompletionAuditResponses,
  GetCompletionBatchData,
  GetCompletionBatchErrors,
  GetCompletionBatchItemData,
  GetCompletionBatchItemErrors,
  GetCompletionBatchItemResponses,
  GetCompletionBatchResponses,
  GetCompletionErrorRateData,
  GetCompletionErrorRateErrors,
  GetCompletionErrorRateResponses,
  GetCompletionUsageData,
  GetCompletionUsageErrors,
  GetCompletionUsageResponses,
  GetEnvironmentByIdData,
  GetEnvironmentByIdErrors,
  GetEnvironmentByIdResponses,
  GetEnvironmentsData,
  GetEnvironmentsErrors,
  GetEnvironmentsResponses,
  GetOauth2AuthorizeData,
  GetOauth2UserinfoData,
  GetOauth2UserinfoResponses,
  GetOauth2WellKnownOpenidConfigurationData,
  GetOauth2WellKnownOpenidConfigurationResponses,
  GetPermissionsData,
  GetPermissionsErrors,
  GetPermissionsResponses,
  GetPoolDefinitionData,
  GetPoolDefinitionErrors,
  GetPoolDefinitionResponses,
  GetRoleByIdData,
  GetRoleByIdErrors,
  GetRoleByIdResponses,
  GetRoleMembersData,
  GetRoleMembersErrors,
  GetRoleMembersResponses,
  GetRolesData,
  GetRolesErrors,
  GetRolesResponses,
  GetUserByIdData,
  GetUserByIdErrors,
  GetUserByIdResponses,
  GetUsersData,
  GetUsersErrors,
  GetUsersResponses,
  GetWorkspaceByIdData,
  GetWorkspaceByIdErrors,
  GetWorkspaceByIdResponses,
  GetWorkspaceMembersData,
  GetWorkspaceMembersErrors,
  GetWorkspaceMembersResponses,
  GetWorkspacesData,
  GetWorkspacesErrors,
  GetWorkspacesResponses,
  HealthcheckControllerHealthcheckData,
  HealthcheckControllerHealthcheckResponses,
  OidcInteractionControllerConsentData,
  OidcInteractionControllerConsentResponses,
  OidcInteractionControllerFederatedCallbackData,
  OidcInteractionControllerFederatedCallbackResponses,
  OidcInteractionControllerFederatedInteractionData,
  OidcInteractionControllerFederatedInteractionResponses,
  OidcInteractionControllerLoginData,
  OidcInteractionControllerLoginResponses,
  OidcInteractionControllerShowChangePasswordInteractionData,
  OidcInteractionControllerShowChangePasswordInteractionResponses,
  OidcInteractionControllerShowInteractionData,
  OidcInteractionControllerShowInteractionResponses,
  OidcInteractionControllerSubmitChangePasswordData,
  OidcInteractionControllerSubmitChangePasswordResponses,
  PostOauth2RevokeData,
  PostOauth2RevokeResponses,
  PostOauth2TokenData,
  PostOauth2TokenResponses,
  UnassignUsersFromRoleData,
  UnassignUsersFromRoleErrors,
  UnassignUsersFromRoleResponses,
  UnassignUsersFromWorkspaceData,
  UnassignUsersFromWorkspaceErrors,
  UnassignUsersFromWorkspaceResponses,
  UpdateAiConnectionData,
  UpdateAiConnectionErrors,
  UpdateAiConnectionResponses,
  UpdateAiResourceData,
  UpdateAiResourceErrors,
  UpdateAiResourceResponses,
  UpdateApiKeyData,
  UpdateApiKeyErrors,
  UpdateApiKeyResponses,
  UpdateEnvironmentData,
  UpdateEnvironmentErrors,
  UpdateEnvironmentResponses,
  UpdateMemberRoleData,
  UpdateMemberRoleErrors,
  UpdateMemberRoleResponses,
  UpdatePoolDefinitionData,
  UpdatePoolDefinitionErrors,
  UpdatePoolDefinitionResponses,
  UpdateRoleData,
  UpdateRoleErrors,
  UpdateRoleResponses,
  UpdateUserData,
  UpdateUserErrors,
  UpdateUserResponses,
  UpdateWorkspaceData,
  UpdateWorkspaceErrors,
  UpdateWorkspaceResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const healthcheckControllerHealthcheck = <
  ThrowOnError extends boolean = false
>(
  options?: Options<HealthcheckControllerHealthcheckData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    HealthcheckControllerHealthcheckResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/healthcheck',
    ...options,
  });

/**
 * List all users
 *
 * Returns a list of all users.
 */
export const getUsers = <ThrowOnError extends boolean = false>(
  options?: Options<GetUsersData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetUsersResponses,
    GetUsersErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/user',
    ...options,
  });

/**
 * Create a new user
 *
 * Creates a new user.
 */
export const createUser = <ThrowOnError extends boolean = false>(
  options: Options<CreateUserData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateUserResponses,
    CreateUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/user',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete a user
 *
 * Deletes a user by its ID.
 */
export const deleteUser = <ThrowOnError extends boolean = false>(
  options: Options<DeleteUserData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteUserResponses,
    DeleteUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/user/{userId}',
    ...options,
  });

/**
 * Get a user by ID
 *
 * Returns a user by ID.
 */
export const getUserById = <ThrowOnError extends boolean = false>(
  options: Options<GetUserByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetUserByIdResponses,
    GetUserByIdErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/user/{userId}',
    ...options,
  });

/**
 * Update a user
 *
 * Updates a user by its ID.
 */
export const updateUser = <ThrowOnError extends boolean = false>(
  options: Options<UpdateUserData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateUserResponses,
    UpdateUserErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/user/{userId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List all available actions for each module
 *
 * Returns a list of all available actions for each module.
 */
export const getPermissions = <ThrowOnError extends boolean = false>(
  options?: Options<GetPermissionsData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetPermissionsResponses,
    GetPermissionsErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/role/permissions',
    ...options,
  });

/**
 * List all roles
 *
 * Returns a list of all roles.
 */
export const getRoles = <ThrowOnError extends boolean = false>(
  options?: Options<GetRolesData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetRolesResponses,
    GetRolesErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/role',
    ...options,
  });

/**
 * Create a new role
 *
 * Creates a new role.
 */
export const createRole = <ThrowOnError extends boolean = false>(
  options: Options<CreateRoleData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateRoleResponses,
    CreateRoleErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/role',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete a role
 *
 * Deletes a role by its ID.
 */
export const deleteRole = <ThrowOnError extends boolean = false>(
  options: Options<DeleteRoleData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteRoleResponses,
    DeleteRoleErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/role/{roleId}',
    ...options,
  });

/**
 * Get a role by ID
 *
 * Returns a role by its ID. Optionally includes user details in the role if `includesUsers` is set to true (default).
 */
export const getRoleById = <ThrowOnError extends boolean = false>(
  options: Options<GetRoleByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetRoleByIdResponses,
    GetRoleByIdErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/role/{roleId}',
    ...options,
  });

/**
 * Update a role
 *
 * Updates a role by its ID.
 */
export const updateRole = <ThrowOnError extends boolean = false>(
  options: Options<UpdateRoleData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateRoleResponses,
    UpdateRoleErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/role/{roleId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List all members of a role
 *
 * Returns a list of all members of a role.
 */
export const getRoleMembers = <ThrowOnError extends boolean = false>(
  options: Options<GetRoleMembersData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetRoleMembersResponses,
    GetRoleMembersErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/role/{roleId}/members',
    ...options,
  });

/**
 * Assign a role to users
 *
 * Assigns a role to users by their IDs.
 */
export const assignUsersToRole = <ThrowOnError extends boolean = false>(
  options: Options<AssignUsersToRoleData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AssignUsersToRoleResponses,
    AssignUsersToRoleErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/role/{roleId}/assign',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Unassign users from a role
 *
 * Unassigns users from a role by their IDs.
 */
export const unassignUsersFromRole = <ThrowOnError extends boolean = false>(
  options: Options<UnassignUsersFromRoleData, ThrowOnError>
) =>
  (options.client ?? client).post<
    UnassignUsersFromRoleResponses,
    UnassignUsersFromRoleErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/role/{roleId}/unassign',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const oidcInteractionControllerShowInteraction = <
  ThrowOnError extends boolean = false
>(
  options: Options<OidcInteractionControllerShowInteractionData, ThrowOnError>
) =>
  (options.client ?? client).get<
    OidcInteractionControllerShowInteractionResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/interaction/{uid}',
    ...options,
  });

export const oidcInteractionControllerShowChangePasswordInteraction = <
  ThrowOnError extends boolean = false
>(
  options: Options<
    OidcInteractionControllerShowChangePasswordInteractionData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    OidcInteractionControllerShowChangePasswordInteractionResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/interaction/{uid}/change-password',
    ...options,
  });

export const oidcInteractionControllerSubmitChangePassword = <
  ThrowOnError extends boolean = false
>(
  options: Options<
    OidcInteractionControllerSubmitChangePasswordData,
    ThrowOnError
  >
) =>
  (options.client ?? client).post<
    OidcInteractionControllerSubmitChangePasswordResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/interaction/{uid}/change-password',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const oidcInteractionControllerLogin = <
  ThrowOnError extends boolean = false
>(
  options: Options<OidcInteractionControllerLoginData, ThrowOnError>
) =>
  (options.client ?? client).post<
    OidcInteractionControllerLoginResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/interaction/{uid}/login',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const oidcInteractionControllerConsent = <
  ThrowOnError extends boolean = false
>(
  options: Options<OidcInteractionControllerConsentData, ThrowOnError>
) =>
  (options.client ?? client).post<
    OidcInteractionControllerConsentResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/interaction/{uid}/consent',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const oidcInteractionControllerFederatedCallback = <
  ThrowOnError extends boolean = false
>(
  options?: Options<
    OidcInteractionControllerFederatedCallbackData,
    ThrowOnError
  >
) =>
  (options?.client ?? client).get<
    OidcInteractionControllerFederatedCallbackResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/interaction/federated/callback',
    ...options,
  });

export const oidcInteractionControllerFederatedInteraction = <
  ThrowOnError extends boolean = false
>(
  options: Options<
    OidcInteractionControllerFederatedInteractionData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    OidcInteractionControllerFederatedInteractionResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/interaction/{uid}/federated',
    ...options,
  });

/**
 * List all user workspaces
 *
 * Returns a list of all workspaces that the authenticated user is a member of. Optionally includes user details in each workspace if `includesUsers` is set to true (default).
 */
export const getWorkspaces = <ThrowOnError extends boolean = false>(
  options?: Options<GetWorkspacesData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetWorkspacesResponses,
    GetWorkspacesErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/workspace',
    ...options,
  });

/**
 * Create a new workspace
 *
 * Creates a new workspace. The authenticated user is automatically added as the owner of the workspace.
 */
export const createWorkspace = <ThrowOnError extends boolean = false>(
  options: Options<CreateWorkspaceData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateWorkspaceResponses,
    CreateWorkspaceErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/workspace',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete a workspace
 *
 * Deletes a workspace by its ID. The authenticated user must be a member of the workspace and have the owner role.
 */
export const deleteWorkspace = <ThrowOnError extends boolean = false>(
  options: Options<DeleteWorkspaceData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteWorkspaceResponses,
    DeleteWorkspaceErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/workspace/{workspaceId}',
    ...options,
  });

/**
 * Get a workspace by ID
 *
 * Returns a workspace by its ID. Optionally includes user details in the workspace if `includesUsers` is set to true (default).
 */
export const getWorkspaceById = <ThrowOnError extends boolean = false>(
  options: Options<GetWorkspaceByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetWorkspaceByIdResponses,
    GetWorkspaceByIdErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/workspace/{workspaceId}',
    ...options,
  });

/**
 * Update a workspace
 *
 * Updates a workspace by its ID. The authenticated user must be a member of the workspace and have the owner role.
 */
export const updateWorkspace = <ThrowOnError extends boolean = false>(
  options: Options<UpdateWorkspaceData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateWorkspaceResponses,
    UpdateWorkspaceErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/workspace/{workspaceId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get the members of a workspace
 *
 * Returns the members of a workspace.
 */
export const getWorkspaceMembers = <ThrowOnError extends boolean = false>(
  options: Options<GetWorkspaceMembersData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetWorkspaceMembersResponses,
    GetWorkspaceMembersErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/workspace/{workspaceId}/members',
    ...options,
  });

/**
 * Update the role of a member of a workspace
 *
 * Updates the role of a member of a workspace by their ID.
 */
export const updateMemberRole = <ThrowOnError extends boolean = false>(
  options: Options<UpdateMemberRoleData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateMemberRoleResponses,
    UpdateMemberRoleErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/workspace/{workspaceId}/members/{userId}/role',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Assign users to a workspace
 *
 * Assigns users to a workspace by their IDs.
 */
export const assignUsersToWorkspace = <ThrowOnError extends boolean = false>(
  options: Options<AssignUsersToWorkspaceData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AssignUsersToWorkspaceResponses,
    AssignUsersToWorkspaceErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/workspace/{workspaceId}/assign',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Unassign users from a workspace
 *
 * Unassigns users from a workspace by their IDs.
 */
export const unassignUsersFromWorkspace = <
  ThrowOnError extends boolean = false
>(
  options: Options<UnassignUsersFromWorkspaceData, ThrowOnError>
) =>
  (options.client ?? client).post<
    UnassignUsersFromWorkspaceResponses,
    UnassignUsersFromWorkspaceErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/workspace/{workspaceId}/unassign',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List all user environments
 *
 * Returns a list of all environments that the authenticated user is a member of. Optionally includes user details in each environment if `includesUsers` is set to true (default).
 */
export const getEnvironments = <ThrowOnError extends boolean = false>(
  options: Options<GetEnvironmentsData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetEnvironmentsResponses,
    GetEnvironmentsErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/environment/{workspaceId}',
    ...options,
  });

/**
 * Create a new environment
 *
 * Creates a new environment. You must be a member of the workspace to create an environment.
 */
export const createEnvironment = <ThrowOnError extends boolean = false>(
  options: Options<CreateEnvironmentData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateEnvironmentResponses,
    CreateEnvironmentErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/environment/{workspaceId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete an environment
 *
 * Deletes an environment by its ID. You must be a member of the workspace to delete an environment.
 */
export const deleteEnvironment = <ThrowOnError extends boolean = false>(
  options: Options<DeleteEnvironmentData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteEnvironmentResponses,
    DeleteEnvironmentErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/environment/{workspaceId}/{environmentId}',
    ...options,
  });

/**
 * Get an environment by ID
 *
 * Returns an environment by its ID. Optionally includes user details in the environment if `includesUsers` is set to true (default).
 */
export const getEnvironmentById = <ThrowOnError extends boolean = false>(
  options: Options<GetEnvironmentByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetEnvironmentByIdResponses,
    GetEnvironmentByIdErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/environment/{workspaceId}/{environmentId}',
    ...options,
  });

/**
 * Update an environment
 *
 * Updates an environment by its ID. You must be a member of the workspace to update an environment.
 */
export const updateEnvironment = <ThrowOnError extends boolean = false>(
  options: Options<UpdateEnvironmentData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateEnvironmentResponses,
    UpdateEnvironmentErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/environment/{workspaceId}/{environmentId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List all AI connections associated with an environment
 *
 * Returns a list of all AI connections associated with an environment. Optionally includes user details in each AI connection if `includesUsers` is set to true (default).
 */
export const getAiConnections = <ThrowOnError extends boolean = false>(
  options: Options<GetAiConnectionsData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetAiConnectionsResponses,
    GetAiConnectionsErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/ai-connection/{workspaceId}/{environmentId}',
    ...options,
  });

/**
 * Create a new AI connection
 *
 * Creates a new AI connection. You must be a member of the workspace to create an AI connection.
 */
export const createAiConnection = <ThrowOnError extends boolean = false>(
  options: Options<CreateAiConnectionData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateAiConnectionResponses,
    CreateAiConnectionErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/ai-connection/{workspaceId}/{environmentId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete an AI connection
 *
 * Deletes an AI connection by its ID. You must be a member of the workspace to delete an AI connection.
 */
export const deleteAiConnection = <ThrowOnError extends boolean = false>(
  options: Options<DeleteAiConnectionData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteAiConnectionResponses,
    DeleteAiConnectionErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/ai-connection/{workspaceId}/{environmentId}/{connectionId}',
    ...options,
  });

/**
 * Get an AI connection by ID
 *
 * Returns an AI connection by its ID. Optionally includes user details in the AI connection if `includesUsers` is set to true (default).
 */
export const getAiConnectionById = <ThrowOnError extends boolean = false>(
  options: Options<GetAiConnectionByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetAiConnectionByIdResponses,
    GetAiConnectionByIdErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/ai-connection/{workspaceId}/{environmentId}/{connectionId}',
    ...options,
  });

/**
 * Update an AI connection
 *
 * Updates an AI connection by its ID. You must be a member of the workspace to update an AI connection.
 */
export const updateAiConnection = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAiConnectionData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateAiConnectionResponses,
    UpdateAiConnectionErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/ai-connection/{workspaceId}/{environmentId}/{connectionId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List all AI providers
 *
 * Returns a list of all AI providers.
 */
export const getAiProviders = <ThrowOnError extends boolean = false>(
  options?: Options<GetAiProvidersData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetAiProvidersResponses,
    GetAiProvidersErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/ai-provider',
    ...options,
  });

/**
 * List all AI resources associated with an environment
 *
 * Returns a list of all AI resources associated with an environment. Optionally includes user details in each AI resource if `includesUsers` is set to true (default).
 */
export const getAiResources = <ThrowOnError extends boolean = false>(
  options: Options<GetAiResourcesData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetAiResourcesResponses,
    GetAiResourcesErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/ai-resource/{workspaceId}/{environmentId}',
    ...options,
  });

/**
 * Create a new AI resource
 *
 * Creates a new AI resource. You must be a member of the workspace to create an AI resource.
 */
export const createAiResource = <ThrowOnError extends boolean = false>(
  options: Options<CreateAiResourceData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateAiResourceResponses,
    CreateAiResourceErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/ai-resource/{workspaceId}/{environmentId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete an AI resource
 *
 * Deletes an AI resource by its ID. You must be a member of the workspace to delete an AI resource.
 */
export const deleteAiResource = <ThrowOnError extends boolean = false>(
  options: Options<DeleteAiResourceData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteAiResourceResponses,
    DeleteAiResourceErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/ai-resource/{workspaceId}/{environmentId}/{resourceId}',
    ...options,
  });

/**
 * Get an AI resource by ID
 *
 * Returns an AI resource by its ID. Optionally includes user details in the AI resource if `includesUsers` is set to true (default).
 */
export const getAiResourceById = <ThrowOnError extends boolean = false>(
  options: Options<GetAiResourceByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetAiResourceByIdResponses,
    GetAiResourceByIdErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/ai-resource/{workspaceId}/{environmentId}/{resourceId}',
    ...options,
  });

/**
 * Update an AI resource
 *
 * Updates an AI resource by its ID. You must be a member of the workspace to update an AI resource.
 */
export const updateAiResource = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAiResourceData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateAiResourceResponses,
    UpdateAiResourceErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/ai-resource/{workspaceId}/{environmentId}/{resourceId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List all API keys associated with an environment
 *
 * Returns a list of all API keys associated with an environment. Optionally includes user details in each API key if `includesUsers` is set to true (default).
 */
export const getApiKeys = <ThrowOnError extends boolean = false>(
  options: Options<GetApiKeysData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetApiKeysResponses,
    GetApiKeysErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/api-key/{workspaceId}/{environmentId}',
    ...options,
  });

/**
 * Create a new API key
 *
 * Creates a new API key. You must be a member of the workspace to create an API key.
 */
export const createApiKey = <ThrowOnError extends boolean = false>(
  options: Options<CreateApiKeyData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateApiKeyResponses,
    CreateApiKeyErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/api-key/{workspaceId}/{environmentId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete an API key
 *
 * Deletes an API key by its ID. You must be a member of the workspace to delete an API key.
 */
export const deleteApiKey = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiKeyData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteApiKeyResponses,
    DeleteApiKeyErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/api-key/{workspaceId}/{environmentId}/{apiKeyId}',
    ...options,
  });

/**
 * Get an API key by ID
 *
 * Returns an API key by its ID. Optionally includes user details in the API key if `includesUsers` is set to true (default).
 */
export const getApiKeyById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiKeyByIdData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetApiKeyByIdResponses,
    GetApiKeyByIdErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/api-key/{workspaceId}/{environmentId}/{apiKeyId}',
    ...options,
  });

/**
 * Update an API key
 *
 * Updates an API key by its ID. You must be a member of the workspace to update an API key.
 */
export const updateApiKey = <ThrowOnError extends boolean = false>(
  options: Options<UpdateApiKeyData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateApiKeyResponses,
    UpdateApiKeyErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/api-key/{workspaceId}/{environmentId}/{apiKeyId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete a pool definition
 *
 * Deletes a pool definition by its workspace and environment. You must be a member of the workspace to delete a pool definition.
 */
export const deletePoolDefinition = <ThrowOnError extends boolean = false>(
  options: Options<DeletePoolDefinitionData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeletePoolDefinitionResponses,
    DeletePoolDefinitionErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/pool-definition/{workspaceId}/{environmentId}',
    ...options,
  });

/**
 * Get a pool definition by workspace and environment
 *
 * Returns a pool definition by its workspace and environment. Optionally includes user details in the pool definition if `includesUsers` is set to true (default).
 */
export const getPoolDefinition = <ThrowOnError extends boolean = false>(
  options: Options<GetPoolDefinitionData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetPoolDefinitionResponses,
    GetPoolDefinitionErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/pool-definition/{workspaceId}/{environmentId}',
    ...options,
  });

/**
 * Created/updated a pool definition
 *
 * Created/updated a pool definition. You must be a member of the workspace to create/update a pool definition.
 */
export const updatePoolDefinition = <ThrowOnError extends boolean = false>(
  options: Options<UpdatePoolDefinitionData, ThrowOnError>
) =>
  (options.client ?? client).post<
    UpdatePoolDefinitionResponses,
    UpdatePoolDefinitionErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/pool-definition/{workspaceId}/{environmentId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * LLM Completion
 *
 * Performs a completion request to the LLM API.
 */
export const completion = <ThrowOnError extends boolean = false>(
  options: Options<CompletionData, ThrowOnError>
) =>
  (options.client ?? client).post<CompletionResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/completion/{workspaceId}/{environmentId}/chat/completions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get the error rate for an AI resource
 *
 * Returns the error rate for an AI resource in the requested window
 */
export const getCompletionErrorRate = <ThrowOnError extends boolean = false>(
  options: Options<GetCompletionErrorRateData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetCompletionErrorRateResponses,
    GetCompletionErrorRateErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/completion-metric/{workspaceId}/{environmentId}/{resourceId}/error-rate',
    ...options,
  });

/**
 * List all completion audits associated with an environment
 *
 * Returns a list of all completion audits associated with an environment.
 */
export const getCompletionAudit = <ThrowOnError extends boolean = false>(
  options: Options<GetCompletionAuditData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetCompletionAuditResponses,
    GetCompletionAuditErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/completion-audit/{workspaceId}/{environmentId}',
    ...options,
  });

/**
 * Query completion usage records
 *
 * Returns a list of completion usage records based on the query parameters
 */
export const getCompletionUsage = <ThrowOnError extends boolean = false>(
  options: Options<GetCompletionUsageData, ThrowOnError>
) =>
  (options.client ?? client).post<
    GetCompletionUsageResponses,
    GetCompletionUsageErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/completion-usage/{workspaceId}/{environmentId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get a completion batch
 *
 * Get a completion batch by its ID
 */
export const getCompletionBatch = <ThrowOnError extends boolean = false>(
  options: Options<GetCompletionBatchData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetCompletionBatchResponses,
    GetCompletionBatchErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/completion-batch/{workspaceId}/{environmentId}/{batchId}',
    ...options,
  });

/**
 * Get a completion batch item
 *
 * Get a completion batch item by its ID
 */
export const getCompletionBatchItem = <ThrowOnError extends boolean = false>(
  options: Options<GetCompletionBatchItemData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetCompletionBatchItemResponses,
    GetCompletionBatchItemErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/completion-batch/{workspaceId}/{environmentId}/{batchId}/{itemId}',
    ...options,
  });

/**
 * Create a completion batch
 *
 * Create a completion batch
 */
export const createCompletionBatch = <ThrowOnError extends boolean = false>(
  options: Options<CreateCompletionBatchData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateCompletionBatchResponses,
    CreateCompletionBatchErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/completion-batch/{workspaceId}/{environmentId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Cancel a completion batch
 *
 * Cancel a completion batch by its ID
 */
export const cancelCompletionBatch = <ThrowOnError extends boolean = false>(
  options: Options<CancelCompletionBatchData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CancelCompletionBatchResponses,
    CancelCompletionBatchErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/completion-batch/{workspaceId}/{environmentId}/{batchId}/cancel',
    ...options,
  });

/**
 * OIDC Authorization Endpoint
 *
 * The authorization endpoint initiates the OAuth2/OpenID Connect flow
 */
export const getOauth2Authorize = <ThrowOnError extends boolean = false>(
  options: Options<GetOauth2AuthorizeData, ThrowOnError>
) =>
  (options.client ?? client).get<unknown, unknown, ThrowOnError>({
    url: '/oauth2/authorize',
    ...options,
  });

/**
 * OIDC Token Endpoint
 *
 * Exchanges authorization codes for access tokens
 */
export const postOauth2Token = <ThrowOnError extends boolean = false>(
  options?: Options<PostOauth2TokenData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    PostOauth2TokenResponses,
    unknown,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    url: '/oauth2/token',
    ...options,
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...options?.headers,
    },
  });

/**
 * Returns claims about the authenticated end-user
 */
export const getOauth2Userinfo = <ThrowOnError extends boolean = false>(
  options?: Options<GetOauth2UserinfoData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetOauth2UserinfoResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/oauth2/userinfo',
    ...options,
  });

/**
 * Token Revocation Endpoint
 *
 * Revokes access or refresh tokens
 */
export const postOauth2Revoke = <ThrowOnError extends boolean = false>(
  options?: Options<PostOauth2RevokeData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    PostOauth2RevokeResponses,
    unknown,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    url: '/oauth2/revoke',
    ...options,
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...options?.headers,
    },
  });

/**
 * OpenID Connect Discovery
 *
 * Returns the OpenID Connect configuration document
 */
export const getOauth2WellKnownOpenidConfiguration = <
  ThrowOnError extends boolean = false
>(
  options?: Options<GetOauth2WellKnownOpenidConfigurationData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetOauth2WellKnownOpenidConfigurationResponses,
    unknown,
    ThrowOnError
  >({ url: '/oauth2/.well-known/openid-configuration', ...options });
