packages:
  - packages/*
  - packages/libs/shared/*
  - examples/*
  - docs/

allowBuilds:
  '@google/genai': true
  '@nestjs/core': true
  '@parcel/watcher': true
  '@scarf/scarf': true
  '@swc/core': true
  argon2: true
  bcrypt: true
  core-js: true
  core-js-pure: true
  esbuild: true
  nx: true
  protobufjs: true
  sharp: true
  unrs-resolver: true

autoInstallPeers: true

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@swc/core'
  - argon2
  - bcrypt
  - core-js
  - core-js-pure
  - esbuild
  - nx
  - protobufjs
  - sharp
  - unrs-resolver
