import { ApiProperty } from '@nestjs/swagger';
import {
  IsDate,
  IsEnum,
  IsInt,
  IsNotEmpty,
  IsOptional,
  IsString,
} from 'class-validator';
import { CompletionResponse } from '../../../ai-provider/ai-provider.types';
import { PublicCompletionBatchRequestStatus } from '../../../storage/entities.generated';
import { completionBatchRequestStatusValues } from '../entity/batch.entity';

export class UpdateCompletionBatchItemDto {
  @ApiProperty({
    description: 'The status of the batch item',
    enum: completionBatchRequestStatusValues,
    enumName: 'CompletionBatchRequestStatus',
    example: PublicCompletionBatchRequestStatus.PENDING,
  })
  @IsEnum(PublicCompletionBatchRequestStatus)
  @IsNotEmpty()
  status: PublicCompletionBatchRequestStatus;

  @ApiProperty({
    description:
      'The response for the batch item (if completed) (openai chat completion response)',
    type: Object,
  })
  @IsOptional()
  response?: CompletionResponse | null;

  @ApiProperty({
    description: 'The timestamp when the item was completed',
    example: '2024-01-01T10:00:00.000Z',
    nullable: true,
    required: false,
    type: 'string',
    format: 'date-time',
  })
  @IsDate()
  @IsOptional()
  completedAt?: Date | null;

  @ApiProperty({
    description: 'Number of output tokens generated by the model',
    example: 42,
  })
  @IsInt()
  @IsOptional()
  outputTokens?: number;

  @ApiProperty({
    description: 'Number of prompt tokens used',
    example: 15,
  })
  @IsInt()
  @IsOptional()
  promptTokens?: number;

  @ApiProperty({
    description: 'Total number of tokens used',
    example: 57,
  })
  @IsInt()
  @IsOptional()
  totalTokens?: number;

  @ApiProperty({
    description: 'The error message if the batch item failed',
    example: 'Request failed: Rate limit exceeded.',
  })
  @IsOptional()
  @IsString()
  errorMessage?: string | null;

  @ApiProperty({
    description: 'The number of times this item has been retried',
    example: 0,
  })
  @IsInt()
  @IsOptional()
  retryCount?: number;
}
