/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export enum PublicProviderType {
  LOCAL = "LOCAL",
  OIDC = "OIDC",
}

export enum PublicWorkspaceUserRole {
  MEMBER = "MEMBER",
  OWNER = "OWNER",
}

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AiConnection {
  allowedModels: ColumnType<string[] | null, string | null, string | null>;
  capacity: ColumnType<any[] | null, string | null, string | null>;
  config: ColumnType<any | null, string | null, string | null>;
  connectionId: Generated<string>;
  createdAt: Generated<Timestamp>;
  createdBy: string;
  description: string | null;
  discoveredCapacity: ColumnType<any | null, string | null, string | null>;
  environmentId: string;
  name: string;
  provider: string;
  updatedAt: Generated<Timestamp>;
  updatedBy: string;
  workspaceId: string;
}

export interface AiResource {
  capacity: ColumnType<any[] | null, string | null, string | null>;
  createdAt: Generated<Timestamp>;
  createdBy: string;
  description: string | null;
  enforceCapacity: Generated<boolean>;
  environmentId: string;
  fallbackModels: ColumnType<any[] | null, string | null, string | null>;
  model: ColumnType<any, string, string | null>;
  resource: string;
  routing: ColumnType<any | null, string | null, string | null>;
  secondaryModels: ColumnType<any[] | null, string | null, string | null>;
  updatedAt: Generated<Timestamp>;
  updatedBy: string;
  useFallback: Generated<boolean>;
  workspaceId: string;
}

export interface ApiKey {
  apiKeyId: Generated<string>;
  capacity: ColumnType<any[] | null, string | null, string | null>;
  createdAt: Generated<Timestamp>;
  createdBy: string;
  description: string | null;
  enabled: Generated<boolean>;
  enforceCapacity: Generated<boolean>;
  environmentId: string;
  hash: string;
  labels: ColumnType<any[] | null, string | null, string | null>;
  lastUsedAt: Timestamp | null;
  maskedKey: string;
  name: string;
  resources: ColumnType<any[], string, string | null>;
  updatedAt: Generated<Timestamp>;
  updatedBy: string;
  workspaceId: string;
}

export interface Environment {
  createdAt: Generated<Timestamp>;
  createdBy: string;
  description: string | null;
  environmentId: Generated<string>;
  name: string;
  updatedAt: Generated<Timestamp>;
  updatedBy: string;
  workspaceId: string;
}

export interface OidcProvider {
  consumed: Generated<boolean>;
  expiresAt: Timestamp | null;
  grantId: string | null;
  id: string;
  payload: Json;
  uid: string | null;
  userCode: string | null;
}

export interface PoolDefinition {
  createdAt: Generated<Timestamp>;
  createdBy: string;
  definition: ColumnType<any[], string, string | null>;
  environmentId: string;
  updatedAt: Generated<Timestamp>;
  updatedBy: string;
  workspaceId: string;
}

export interface User {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: Generated<boolean>;
  firstName: string;
  id: Generated<string>;
  lastName: string;
  name: string;
  passwordHash: string | null;
  pictureUrl: string | null;
  providerId: string;
  providerMetadata: Json | null;
  providerType: PublicProviderType;
  updatedAt: Generated<Timestamp>;
  username: string;
}

export interface Workspace {
  createdAt: Generated<Timestamp>;
  createdBy: string;
  description: string | null;
  name: string;
  updatedAt: Generated<Timestamp>;
  updatedBy: string;
  workspaceId: Generated<string>;
}

export interface WorkspaceUser {
  addedAt: Generated<Timestamp>;
  addedBy: string;
  role: PublicWorkspaceUserRole;
  userId: string;
  workspaceId: string;
}

export interface DB {
  aiConnections: AiConnection;
  aiResources: AiResource;
  apiKeys: ApiKey;
  environments: Environment;
  oidcProvider: OidcProvider;
  poolDefinitions: PoolDefinition;
  users: User;
  workspaces: Workspace;
  workspaceUsers: WorkspaceUser;
}
