/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export enum PublicCompletionAuditType {
  COMPLETION = "COMPLETION",
  COMPLETION_BATCH = "COMPLETION_BATCH",
}

export enum PublicCompletionBatchRequestStatus {
  CANCELLED = "CANCELLED",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  PENDING = "PENDING",
  RUNNING = "RUNNING",
}

export enum PublicCompletionBatchRequestType {
  ASYNC = "ASYNC",
  CALLBACK = "CALLBACK",
  SYNC = "SYNC",
}

export enum PublicProviderType {
  LOCAL = "LOCAL",
  OIDC = "OIDC",
}

export enum PublicWorkspaceUserRole {
  MEMBER = "MEMBER",
  OWNER = "OWNER",
}

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AiConnection {
  allowedModels: ColumnType<string[] | null, string | null, string | null>;
  capacity: ColumnType<any[] | null, string | null, string | null>;
  config: ColumnType<any | null, string | null, string | null>;
  connectionId: Generated<string>;
  createdAt: Generated<Timestamp>;
  createdBy: string;
  description: string | null;
  discoveredCapacity: ColumnType<any | null, string | null, string | null>;
  environmentId: string;
  name: string;
  provider: string;
  updatedAt: Generated<Timestamp>;
  updatedBy: string;
  workspaceId: string;
}

export interface AiResource {
  capacity: ColumnType<any[] | null, string | null, string | null>;
  createdAt: Generated<Timestamp>;
  createdBy: string;
  description: string | null;
  enforceCapacity: Generated<boolean>;
  environmentId: string;
  fallbackModels: ColumnType<any[] | null, string | null, string | null>;
  model: ColumnType<any, string, string | null>;
  name: string;
  resourceId: Generated<string>;
  routing: ColumnType<any | null, string | null, string | null>;
  secondaryModels: ColumnType<any[] | null, string | null, string | null>;
  updatedAt: Generated<Timestamp>;
  updatedBy: string;
  useFallback: Generated<boolean>;
  workspaceId: string;
}

export interface ApiKey {
  apiKeyId: Generated<string>;
  capacity: ColumnType<any[] | null, string | null, string | null>;
  createdAt: Generated<Timestamp>;
  createdBy: string;
  description: string | null;
  enabled: Generated<boolean>;
  enforceCapacity: Generated<boolean>;
  environmentId: string;
  hash: string;
  labels: ColumnType<any[] | null, string | null, string | null>;
  maskedKey: string;
  name: string;
  resources: ColumnType<any[], string, string | null>;
  updatedAt: Generated<Timestamp>;
  updatedBy: string;
  workspaceId: string;
}

export interface CompletionAudit {
  apiKeyId: string | null;
  batchId: string | null;
  connectionId: string | null;
  correlationId: string | null;
  duration: number;
  environmentId: string;
  errorMessage: string | null;
  events: ColumnType<any[] | null, string | null, string | null>;
  failureReason: string | null;
  id: Generated<string>;
  model: string | null;
  provider: string | null;
  requestId: string;
  requestPayload: ColumnType<any | null, string | null, string | null>;
  resourceId: string | null;
  responseData: ColumnType<any | null, string | null, string | null>;
  responseHeaders: ColumnType<any | null, string | null, string | null>;
  sourceIp: string | null;
  statusCode: number;
  timestamp: Timestamp;
  type: PublicCompletionAuditType;
  userId: string | null;
  workspaceId: string;
}

export interface CompletionBatch {
  batchId: Generated<string>;
  callbackOptions: ColumnType<any | null, string | null, string | null>;
  capacity: ColumnType<any[] | null, string | null, string | null>;
  completed: Generated<number>;
  completedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  createdByApiKeyId: string | null;
  createdByUserId: string | null;
  environmentId: string;
  errorMessage: string | null;
  failed: Generated<number>;
  pending: Generated<number>;
  running: Generated<number>;
  status: PublicCompletionBatchRequestStatus;
  timestamp: Timestamp;
  totalCompletionTokens: Generated<number>;
  totalEstimatedPromptTokens: Generated<number>;
  totalItems: Generated<number>;
  totalPromptTokens: Generated<number>;
  type: PublicCompletionBatchRequestType;
  updatedAt: Generated<Timestamp>;
  workspaceId: string;
}

export interface CompletionBatchItem {
  batchId: string;
  completedAt: Timestamp | null;
  completionTokens: Generated<number>;
  createdAt: Generated<Timestamp>;
  environmentId: string;
  errorMessage: string | null;
  estimatedPromptTokens: Generated<number>;
  itemId: Generated<string>;
  promptTokens: Generated<number>;
  request: ColumnType<any | null, string | null, string | null>;
  resourceId: string;
  response: ColumnType<any | null, string | null, string | null>;
  retryCount: Generated<number>;
  status: PublicCompletionBatchRequestStatus;
  totalTokens: Generated<number>;
  workspaceId: string;
}

export interface Environment {
  createdAt: Generated<Timestamp>;
  createdBy: string;
  description: string | null;
  environmentId: Generated<string>;
  name: string;
  updatedAt: Generated<Timestamp>;
  updatedBy: string;
  workspaceId: string;
}

export interface GlobalSecret {
  createdAt: Generated<Timestamp>;
  description: string | null;
  name: string;
  secretId: Generated<string>;
  value: string;
}

export interface OidcProvider {
  consumed: Generated<boolean>;
  expiresAt: Timestamp | null;
  grantId: string | null;
  id: string;
  payload: Json;
  uid: string | null;
  userCode: string | null;
}

export interface PoolDefinition {
  createdAt: Generated<Timestamp>;
  createdBy: string;
  definition: ColumnType<any[], string, string | null>;
  environmentId: string;
  updatedAt: Generated<Timestamp>;
  updatedBy: string;
  workspaceId: string;
}

export interface QuestdbKyselyMigration {
  name: string;
  timestamp: string;
}

export interface QuestdbKyselyMigrationLock {
  id: string;
  isLocked: Generated<number>;
}

export interface Role {
  createdAt: Generated<Timestamp>;
  createdBy: string;
  description: string | null;
  name: string;
  policy: ColumnType<any | null, string | null, string | null>;
  roleId: Generated<string>;
  updatedAt: Generated<Timestamp>;
  updatedBy: string;
}

export interface UserRole {
  assignedAt: Generated<Timestamp>;
  assignedBy: string;
  roleId: string;
  userId: string;
}

export interface User {
  createdAt: Generated<Timestamp>;
  createdBy: string | null;
  email: string;
  emailVerified: Generated<boolean>;
  firstName: string;
  id: Generated<string>;
  lastName: string;
  name: string;
  passwordHash: string | null;
  pictureUrl: string | null;
  providerId: string;
  providerMetadata: Json | null;
  providerType: PublicProviderType;
  updatedAt: Generated<Timestamp>;
  updatedBy: string | null;
  username: string;
}

export interface Workspace {
  createdAt: Generated<Timestamp>;
  createdBy: string;
  description: string | null;
  name: string;
  updatedAt: Generated<Timestamp>;
  updatedBy: string;
  workspaceId: Generated<string>;
}

export interface WorkspaceUser {
  addedAt: Generated<Timestamp>;
  addedBy: string;
  role: PublicWorkspaceUserRole;
  userId: string;
  workspaceId: string;
}

export interface DB {
  aiConnections: AiConnection;
  aiResources: AiResource;
  apiKeys: ApiKey;
  completionAudit: CompletionAudit;
  completionBatch: CompletionBatch;
  completionBatchItems: CompletionBatchItem;
  environments: Environment;
  globalSecrets: GlobalSecret;
  oidcProvider: OidcProvider;
  poolDefinitions: PoolDefinition;
  questdbKyselyMigration: QuestdbKyselyMigration;
  questdbKyselyMigrationLock: QuestdbKyselyMigrationLock;
  roles: Role;
  userRoles: UserRole;
  users: User;
  workspaces: Workspace;
  workspaceUsers: WorkspaceUser;
}
