CREATE USER vmxai WITH PASSWORD 'password';
CREATE USER "vmxai-ro" WITH PASSWORD 'password';

CREATE SCHEMA vmxai;

GRANT USAGE ON SCHEMA public TO vmxai;
GRANT USAGE ON SCHEMA public to "vmxai-ro";
GRANT USAGE ON SCHEMA vmxai to "vmxai";
GRANT USAGE ON SCHEMA vmxai to "vmxai-ro";

ALTER DEFAULT PRIVILEGES IN SCHEMA vmxai GRANT SELECT ON TABLES TO "vmxai-ro";
ALTER DEFAULT PRIVILEGES IN SCHEMA vmxai GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO vmxai;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO vmxai;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO "vmxai-ro";
