// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type HealthcheckResponseDto = {
    /**
     * The status of the healthcheck
     */
    status: string;
};

/**
 * The error code
 */
export enum ErrorCode {
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    OIDC_NOT_CONFIGURED = 'OIDC_NOT_CONFIGURED',
    OIDC_RESPONSE_ERROR = 'OIDC_RESPONSE_ERROR',
    OIDC_CLAIMS_NOT_AVAILABLE = 'OIDC_CLAIMS_NOT_AVAILABLE',
    OIDC_EMAIL_NOT_AVAILABLE = 'OIDC_EMAIL_NOT_AVAILABLE',
    OIDC_EMAIL_MISMATCH = 'OIDC_EMAIL_MISMATCH',
    OIDC_PROVIDER_ID_MISMATCH = 'OIDC_PROVIDER_ID_MISMATCH',
    WORKSPACE_NOT_MEMBER = 'WORKSPACE_NOT_MEMBER',
    WORKSPACE_NOT_FOUND = 'WORKSPACE_NOT_FOUND',
    WORKSPACE_ACTION_NOT_ALLOWED = 'WORKSPACE_ACTION_NOT_ALLOWED',
    WORKSPACE_INSUFFICIENT_PERMISSIONS = 'WORKSPACE_INSUFFICIENT_PERMISSIONS',
    ENVIRONMENT_NOT_MEMBER = 'ENVIRONMENT_NOT_MEMBER',
    ENVIRONMENT_NOT_FOUND = 'ENVIRONMENT_NOT_FOUND',
    AI_CONNECTION_NOT_FOUND = 'AI_CONNECTION_NOT_FOUND',
    AI_CONNECTION_CONFIG_INVALID = 'AI_CONNECTION_CONFIG_INVALID',
    AI_RESOURCE_NOT_FOUND = 'AI_RESOURCE_NOT_FOUND',
    AI_RESOURCE_ALREADY_EXISTS = 'AI_RESOURCE_ALREADY_EXISTS',
    POOL_DEFINITION_NOT_FOUND = 'POOL_DEFINITION_NOT_FOUND',
    AI_PROVIDER_NOT_FOUND = 'AI_PROVIDER_NOT_FOUND',
    API_KEY_NOT_FOUND = 'API_KEY_NOT_FOUND',
    API_KEY_RESOURCE_NOT_AUTHORIZED = 'API_KEY_RESOURCE_NOT_AUTHORIZED',
    COMPLETION_SECONDARY_MODEL_NOT_FOUND = 'COMPLETION_SECONDARY_MODEL_NOT_FOUND',
    COMPLETION_BATCH_NOT_FOUND = 'COMPLETION_BATCH_NOT_FOUND',
    COMPLETION_BATCH_ITEM_NOT_FOUND = 'COMPLETION_BATCH_ITEM_NOT_FOUND'
}

export type ServiceError = {
    /**
     * The error message
     */
    errorMessage: string;
    /**
     * The error code
     */
    errorCode: ErrorCode;
    /**
     * The error details
     */
    details: {
        [key: string]: unknown;
    };
};

export type UserEntity = {
    /**
     * The unique identifier for the user (UUID)
     */
    id: string;
    /**
     * The name of the user
     */
    name: string;
    /**
     * The first name of the user
     */
    firstName: string;
    /**
     * The last name of the user
     */
    lastName: string;
    /**
     * The username of the user, by default it is the email address
     */
    username: string;
    /**
     * The email address of the user
     */
    email: string;
    /**
     * Whether the email address of the user has been verified
     */
    emailVerified: boolean;
    /**
     * The URL of the user's profile picture
     */
    pictureUrl?: string | null;
    /**
     * The type of provider used by the user
     */
    providerType: 'LOCAL' | 'OIDC';
    /**
     * The provider identifier for the user
     */
    providerId: string;
    /**
     * The date and time the user was created
     */
    createdAt: string;
    /**
     * The date and time the user was last updated
     */
    updatedAt: string;
    /**
     * The provider specific metadata for the user (e.g claims)
     */
    providerMetadata?: {
        [key: string]: unknown;
    } | null;
};

export type LoginDto = {
    /**
     * The username or email address of the user
     */
    username: string;
    /**
     * The password of the user
     */
    password: string;
};

export type ConsentDto = {
    /**
     * The consent value
     */
    consent: 'yes' | 'no';
};

export type UserRelationDto = {
    /**
     * The unique identifier for the user (UUID)
     */
    id: string;
    /**
     * The name of the user
     */
    name: string;
    /**
     * The first name of the user
     */
    firstName: string;
    /**
     * The last name of the user
     */
    lastName: string;
    /**
     * The username of the user, by default it is the email address
     */
    username: string;
    /**
     * The email address of the user
     */
    email: string;
    /**
     * Whether the email address of the user has been verified
     */
    emailVerified: boolean;
    /**
     * The URL of the user's profile picture
     */
    pictureUrl?: string | null;
    /**
     * The type of provider used by the user
     */
    providerType: 'LOCAL' | 'OIDC';
    /**
     * The provider identifier for the user
     */
    providerId: string;
    /**
     * The provider specific metadata for the user (e.g claims)
     */
    providerMetadata?: {
        [key: string]: unknown;
    } | null;
    /**
     * The date and time the user was created
     */
    createdAt: string;
    /**
     * The date and time the user was last updated
     */
    updatedAt: string;
};

export type EnvironmentRelationDto = {
    /**
     * The unique identifier for the environment (UUID)
     */
    environmentId: string;
    /**
     * The workspace that the environment is associated with
     */
    workspaceId: string;
    /**
     * The name of the environment
     */
    name: string;
    /**
     * The description of the environment
     */
    description?: string | null;
    /**
     * The user who created the workspace
     */
    createdBy: string;
    /**
     * The user who created the workspace
     */
    createdByUser?: UserRelationDto | null;
    /**
     * The user who last updated the workspace
     */
    updatedBy: string;
    /**
     * The user who last updated the workspace
     */
    updatedByUser?: UserRelationDto | null;
    /**
     * The date and time the environment was created
     */
    createdAt: string;
    /**
     * The date and time the environment was last updated
     */
    updatedAt: string;
};

export type WorkspaceEntity = {
    /**
     * The unique identifier for the workspace (UUID)
     */
    workspaceId: string;
    /**
     * The name of the workspace
     */
    name: string;
    /**
     * The description of the workspace
     */
    description?: string | null;
    /**
     * The date and time the workspace was created
     */
    createdAt: string;
    /**
     * The date and time the workspace was last updated
     */
    updatedAt: string;
    /**
     * The user who created the workspace
     */
    createdBy: string;
    /**
     * The user who created the workspace
     */
    createdByUser?: UserRelationDto | null;
    /**
     * The user who last updated the workspace
     */
    updatedBy: string;
    /**
     * The user who last updated the workspace
     */
    updatedByUser?: UserRelationDto | null;
    /**
     * The environments in the workspace
     */
    environments?: Array<EnvironmentRelationDto> | null;
};

export type CreateWorkspaceDto = {
    /**
     * The name of the workspace
     */
    name: string;
    /**
     * The description of the workspace
     */
    description?: string | null;
};

export type UpdateWorkspaceDto = {
    /**
     * The name of the workspace
     */
    name?: string;
    /**
     * The description of the workspace
     */
    description?: string | null;
};

export type EnvironmentEntity = {
    /**
     * The unique identifier for the environment (UUID)
     */
    environmentId: string;
    /**
     * The workspace that the environment is associated with
     */
    workspaceId: string;
    /**
     * The name of the environment
     */
    name: string;
    /**
     * The description of the environment
     */
    description?: string | null;
    /**
     * The date and time the workspace was created
     */
    createdAt: string;
    /**
     * The date and time the workspace was last updated
     */
    updatedAt: string;
    /**
     * The user who created the workspace
     */
    createdBy: string;
    /**
     * The user who created the workspace
     */
    createdByUser?: UserRelationDto | null;
    /**
     * The user who last updated the workspace
     */
    updatedBy: string;
    /**
     * The user who last updated the workspace
     */
    updatedByUser?: UserRelationDto | null;
};

export type CreateEnvironmentDto = {
    /**
     * The name of the environment
     */
    name: string;
    /**
     * The description of the workspace
     */
    description?: string | null;
};

export type UpdateEnvironmentDto = {
    /**
     * The name of the environment
     */
    name?: string;
    /**
     * The description of the environment
     */
    description?: string | null;
};

/**
 * The period of the capacity
 */
export enum CapacityPeriod {
    MINUTE = 'minute',
    HOUR = 'hour',
    DAY = 'day',
    WEEK = 'week',
    MONTH = 'month',
    LIFETIME = 'lifetime'
}

/**
 * The dimension of the capacity
 */
export enum CapacityDimension {
    SOURCE_IP = 'source-ip'
}

export type CapacityEntity = {
    /**
     * The period of the capacity
     */
    period: CapacityPeriod;
    /**
     * The number of requests allowed per period
     */
    requests?: number | null;
    /**
     * The number of tokens allowed per period
     */
    tokens?: number | null;
    /**
     * Whether the capacity is enabled
     */
    enabled?: boolean | null;
    /**
     * The dimension of the capacity
     */
    dimension?: CapacityDimension | null;
};

export type DiscoveredCapacityEntity = {
    /**
     * The models of the discovered capacity (JSON object)
     */
    models: {
        [key: string]: DiscoveredCapacityEntry;
    };
};

export type AiConnectionEntity = {
    /**
     * The unique identifier for the AI connection (UUID)
     */
    connectionId: string;
    /**
     * The workspace that the AI connection is associated with
     */
    workspaceId: string;
    /**
     * The environment that the AI connection is associated with
     */
    environmentId: string;
    /**
     * The name of the AI connection
     */
    name: string;
    /**
     * The description of the AI connection
     */
    description?: string | null;
    /**
     * The provider of the AI connection
     */
    provider: string;
    /**
     * The allowed models of the AI connection
     */
    allowedModels?: Array<string> | null;
    /**
     * The capacities of the AI connection (JSON array)
     */
    capacity?: Array<CapacityEntity> | null;
    /**
     * The automatically discovered capacity of the AI connection (JSON object)
     */
    discoveredCapacity?: DiscoveredCapacityEntity | null;
    /**
     * The configuration of the AI connection (JSON object)
     */
    config?: {
        [key: string]: unknown;
    } | null;
    /**
     * The date and time the AI connection was created
     */
    createdAt: string;
    /**
     * The date and time the AI connection was last updated
     */
    updatedAt: string;
    /**
     * The user who created the AI connection
     */
    createdBy: string;
    /**
     * The user who created the AI connection
     */
    createdByUser?: UserRelationDto | null;
    /**
     * The user who last updated the AI connection
     */
    updatedBy: string;
    /**
     * The user who last updated the AI connection
     */
    updatedByUser?: UserRelationDto | null;
};

export type CreateAiConnectionDto = {
    /**
     * The name of the AI connection
     */
    name: string;
    /**
     * The description of the AI connection
     */
    description?: string | null;
    /**
     * The provider of the AI connection
     */
    provider: string;
    /**
     * The allowed models of the AI connection
     */
    allowedModels?: Array<string> | null;
    /**
     * The capacities of the AI connection (JSON array)
     */
    capacity?: Array<CapacityEntity> | null;
    /**
     * The configuration of the AI connection (JSON object)
     */
    config?: {
        [key: string]: unknown;
    } | null;
};

export type UpdateAiConnectionDto = {
    /**
     * The name of the AI connection
     */
    name?: string | null;
    /**
     * The description of the AI connection
     */
    description?: string | null;
    /**
     * The provider of the AI connection
     */
    provider?: string | null;
    /**
     * The allowed models of the AI connection
     */
    allowedModels?: Array<string> | null;
    /**
     * The capacities of the AI connection (JSON array)
     */
    capacity?: Array<CapacityEntity> | null;
    /**
     * The configuration of the AI connection (JSON object)
     */
    config?: {
        [key: string]: unknown;
    } | null;
};

export type AiProviderConnectionAccordionComponentDto = {
    /**
     * The component type (should be 'accordion')
     */
    type: 'accordion';
    /**
     * Accordion title
     */
    title: string;
    /**
     * Accordion content elements, may include typography or editor components
     */
    elements: Array<AiProviderConnectionTypographyComponentDto | AiProviderConnectionEditorComponentDto>;
};

export type AiProviderConnectionButtonComponentDto = {
    /**
     * The component type (should be 'link-button')
     */
    type: 'link-button';
    /**
     * Text content of the button
     */
    content: string;
    /**
     * Style overrides for the button component
     */
    sx?: {
        [key: string]: unknown;
    } | null;
    /**
     * URL to which the button navigates
     */
    url: string;
    /**
     * Target attribute for the link, e.g., _blank
     */
    target?: string | null;
    /**
     * Helper text to be displayed near the button
     */
    helperText?: string | null;
};

export type AiProviderConnectionTypographyComponentDto = {
    /**
     * The component type (should be 'typography')
     */
    type: 'typography';
    /**
     * The text content to display
     */
    content: string;
    /**
     * Typography style variant
     */
    variant: 'body1' | 'body2' | 'caption' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'subtitle1' | 'subtitle2';
    /**
     * Style overrides for the typography component
     */
    sx?: {
        [key: string]: unknown;
    } | null;
};

export type AiProviderConnectionEditorComponentDto = {
    /**
     * The component type (should be 'editor')
     */
    type: 'editor';
    /**
     * Content/code to display in the editor
     */
    content: string;
    /**
     * Programming language for syntax highlighting
     */
    language: string;
    /**
     * Height of the editor, e.g., 200px
     */
    height: string;
    /**
     * Whether the editor is read-only
     */
    readOnly?: boolean | null;
    /**
     * Message to display if the editor is read-only
     */
    readOnlyMessage?: string | null;
};

export type AiProviderLogoDto = {
    /**
     * The URL of the AI provider logo
     */
    url: string;
};

export type AiProviderConnectionDto = {
    /**
     * JSONSchema definition or data required for connection
     */
    form: {
        [key: string]: unknown;
    };
    /**
     * UI components to customize the connection experience
     */
    uiComponents?: Array<AiProviderConnectionAccordionComponentDto | AiProviderConnectionButtonComponentDto> | null;
};

export type AiProviderConfigDto = {
    /**
     * Logo for the AI provider
     */
    logo: AiProviderLogoDto;
    /**
     * Connection form and UI information
     */
    connection: AiProviderConnectionDto;
};

export type AiProviderDto = {
    /**
     * The unique provider identifier
     */
    id: string;
    /**
     * Display name of the provider
     */
    name: string;
    /**
     * Description of the AI provider
     */
    description?: string | null;
    /**
     * Configuration details for the provider
     */
    config: AiProviderConfigDto;
    /**
     * Default model for the provider
     */
    defaultModel: string;
};

/**
 * Comparator for the routing condition
 */
export enum RoutingComparator {
    EQUAL = 'EQUAL',
    NOT_EQUAL = 'NOT_EQUAL',
    GREATER_THAN = 'GREATER_THAN',
    GREATER_THAN_OR_EQUAL = 'GREATER_THAN_OR_EQUAL',
    LESS_THAN = 'LESS_THAN',
    LESS_THAN_OR_EQUAL = 'LESS_THAN_OR_EQUAL',
    CONTAINS = 'CONTAINS',
    NOT_CONTAINS = 'NOT_CONTAINS',
    STARTS_WITH = 'STARTS_WITH',
    ENDS_WITH = 'ENDS_WITH',
    PATTERN = 'PATTERN',
    IN = 'IN',
    NOT_IN = 'NOT_IN',
    EXISTS = 'EXISTS'
}

/**
 * The type of the routing condition value
 */
export enum RoutingConditionType {
    STRING = 'STRING',
    NUMBER = 'NUMBER',
    BOOLEAN = 'BOOLEAN',
    COMMA_DELIMITED_LIST = 'COMMA_DELIMITED_LIST',
    JSON_OBJECT = 'JSON_OBJECT',
    JSON_ARRAY = 'JSON_ARRAY'
}

export type AiResourceRoutingConditionValue = {
    /**
     * The type of the routing condition value
     */
    type: RoutingConditionType;
    /**
     * An optional expression EJS for the condition value
     */
    expression?: string;
};

export type AiResourceRoutingCondition = {
    /**
     * The unique ID of the routing condition
     */
    id: string;
    /**
     * Label for the routing condition
     */
    label: string;
    /**
     * The EJS expression to evaluate for the condition
     */
    expression: string;
    /**
     * Comparator for the routing condition
     */
    comparator: RoutingComparator;
    /**
     * Value for the routing condition
     */
    value: AiResourceRoutingConditionValue;
};

export type DiscoveredCapacityEntry = {
    /**
     * The date and time the discovered capacity was last updated
     */
    updatedAt: string;
    /**
     * The capacities of the discovered capacity (JSON array)
     */
    capacity: Array<CapacityEntity>;
    /**
     * The error message of the discovered capacity
     */
    errorMessage?: string | null;
};

export type AiResourceModelConfigEntity = {
    /**
     * The provider of the AI resource model
     */
    provider: string;
    /**
     * The model of the AI resource model
     */
    model: string;
    /**
     * The AI connection ID of the AI resource model
     */
    connectionId: string;
};

/**
 * Logical operator for grouping conditions
 */
export enum RoutingOperator {
    AND = 'AND',
    OR = 'OR'
}

/**
 * Action to take if group matches
 */
export enum RoutingAction {
    BLOCK = 'BLOCK',
    CALL_MODEL = 'CALL_MODEL'
}

/**
 * UI or advanced routing mode
 */
export enum RoutingMode {
    UI = 'UI',
    ADVANCED = 'ADVANCED'
}

export type AiResourceRoutingModelConfig = {
    /**
     * The provider of the AI resource model
     */
    provider: string;
    /**
     * The model of the AI resource model
     */
    model: string;
    /**
     * The AI connection ID of the AI resource model
     */
    connectionId: string;
    /**
     * Traffic percentage sent to this model config, empty means all traffic
     */
    traffic?: number;
};

export type AiRoutingConditionGroup = {
    /**
     * Optional ID for the condition group
     */
    id?: string;
    /**
     * Description of the condition group
     */
    description?: string;
    /**
     * Logical operator for grouping conditions
     */
    operator: RoutingOperator;
    /**
     * List of routing conditions
     */
    conditions: Array<AiResourceRoutingCondition | AiRoutingConditionGroup>;
    /**
     * Action to take if group matches
     */
    action: RoutingAction;
    /**
     * UI or advanced routing mode
     */
    mode: RoutingMode;
    /**
     * Optional expression EJS for group
     */
    expression?: string;
    /**
     * Model configuration to use if conditions match
     */
    then?: AiResourceRoutingModelConfig;
    /**
     * Whether this group is enabled
     */
    enabled?: boolean;
};

export type AiResourceModelRoutingEntity = {
    /**
     * Whether routing is enabled
     */
    enabled: boolean;
    /**
     * Condition groups for routing
     */
    conditions: Array<AiRoutingConditionGroup>;
};

export type AiResourceEntity = {
    /**
     * Resource unique identifier
     */
    resource: string;
    /**
     * Workspace ID associated with the resource
     */
    workspaceId: string;
    /**
     * Environment ID associated with the resource
     */
    environmentId: string;
    /**
     * Description of the AI resource
     */
    description?: string | null;
    /**
     * Primary model configuration for the resource
     */
    model: AiResourceModelConfigEntity;
    /**
     * Whether fallback models are used if primary fails
     */
    useFallback: boolean;
    /**
     * List of fallback model configurations
     */
    fallbackModels?: Array<AiResourceModelConfigEntity> | null;
    /**
     * List of secondary (non-fallback) models for A/B/ensemble use
     */
    secondaryModels?: Array<AiResourceModelConfigEntity> | null;
    /**
     * Routing rules for this resource
     */
    routing?: AiResourceModelRoutingEntity | null;
    /**
     * Capacity configuration entries for rate limiting
     */
    capacity?: Array<CapacityEntity> | null;
    /**
     * Whether capacity is enforced for requests to this resource
     */
    enforceCapacity: boolean;
    /**
     * Timestamp when the resource was created
     */
    createdAt: string;
    /**
     * Timestamp when the resource was last updated
     */
    updatedAt: string;
    /**
     * User ID who created the resource
     */
    createdBy: string;
    /**
     * User details of who created the resource
     */
    createdByUser?: UserRelationDto | null;
    /**
     * User ID who last updated the resource
     */
    updatedBy: string;
    /**
     * User details of who last updated the resource
     */
    updatedByUser?: UserRelationDto | null;
};

export type CreateAiResourceDto = {
    /**
     * Resource unique identifier
     */
    resource: string;
    /**
     * Description of the AI resource
     */
    description?: string | null;
    /**
     * Primary model configuration for the resource
     */
    model: AiResourceModelConfigEntity;
    /**
     * Whether fallback models are used if primary fails
     */
    useFallback: boolean;
    /**
     * List of fallback model configurations
     */
    fallbackModels?: Array<AiResourceModelConfigEntity> | null;
    /**
     * List of secondary (non-fallback) models for A/B/ensemble use
     */
    secondaryModels?: Array<AiResourceModelConfigEntity> | null;
    /**
     * Routing rules for this resource
     */
    routing?: AiResourceModelRoutingEntity | null;
    /**
     * Capacity configuration entries for rate limiting
     */
    capacity?: Array<CapacityEntity> | null;
    /**
     * Whether capacity is enforced for requests to this resource
     */
    enforceCapacity: boolean;
    /**
     * The API keys to assign to the AI resource
     */
    assignApiKeys?: Array<string> | null;
};

export type UpdateAiResourceDto = {
    /**
     * Resource unique identifier
     */
    resource?: string;
    /**
     * Description of the AI resource
     */
    description?: string | null;
    /**
     * Primary model configuration for the resource
     */
    model?: AiResourceModelConfigEntity;
    /**
     * Whether fallback models are used if primary fails
     */
    useFallback?: boolean;
    /**
     * List of fallback model configurations
     */
    fallbackModels?: Array<AiResourceModelConfigEntity> | null;
    /**
     * List of secondary (non-fallback) models for A/B/ensemble use
     */
    secondaryModels?: Array<AiResourceModelConfigEntity> | null;
    /**
     * Routing rules for this resource
     */
    routing?: AiResourceModelRoutingEntity | null;
    /**
     * Capacity configuration entries for rate limiting
     */
    capacity?: Array<CapacityEntity> | null;
    /**
     * Whether capacity is enforced for requests to this resource
     */
    enforceCapacity?: boolean;
    /**
     * The API keys to assign to the AI resource
     */
    assignApiKeys?: Array<string> | null;
};

export type PoolDefinitionEntry = {
    /**
     * The name of the pool entry
     */
    name: string;
    /**
     * The rank or priority order of the entry
     */
    rank: number;
    /**
     * Minimum % of the AI connection capacity that must be reserved for this entry
     */
    minReservation: number;
    /**
     * Maximum % of the AI connection capacity that can be reserved for this entry
     */
    maxReservation: number;
    /**
     * Resource identifiers included in this entry
     */
    resources: Array<string>;
};

export type PoolDefinitionEntity = {
    /**
     * Workspace UUID
     */
    workspaceId: string;
    /**
     * Environment UUID
     */
    environmentId: string;
    /**
     * List of pool definition entries
     */
    definition: Array<PoolDefinitionEntry>;
    /**
     * Timestamp when the pool definition was created
     */
    createdAt: string;
    /**
     * Timestamp when the pool definition was last updated
     */
    updatedAt: string;
    /**
     * User ID who created the pool definition
     */
    createdBy: string;
    /**
     * User who created the pool definition
     */
    createdByUser?: UserRelationDto | null;
    /**
     * User ID who last updated the pool definition
     */
    updatedBy: string;
    /**
     * User who last updated the pool definition
     */
    updatedByUser?: UserRelationDto | null;
};

export type UpsertPoolDefinitionDto = {
    /**
     * List of pool definition entries
     */
    definition: Array<PoolDefinitionEntry>;
};

export type ApiKeyEntity = {
    /**
     * The unique identifier for the API key (UUID)
     */
    apiKeyId: string;
    /**
     * The workspace that the API key is associated with
     */
    workspaceId: string;
    /**
     * The environment that the API key is associated with
     */
    environmentId: string;
    /**
     * The name of the API key
     */
    name: string;
    /**
     * The description of the API key
     */
    description?: string | null;
    /**
     * Whether the API key is enabled
     */
    enabled: boolean;
    /**
     * The resources that the API key is associated with
     */
    resources: Array<string>;
    /**
     * The labels that the API key is associated with
     */
    labels?: Array<string> | null;
    /**
     * Whether capacity is enforced for requests to the API key
     */
    enforceCapacity: boolean;
    /**
     * The capacities of the API key (JSON array)
     */
    capacity?: Array<CapacityEntity> | null;
    /**
     * The masked key of the API key
     */
    maskedKey: string;
    /**
     * The date and time the API key was created
     */
    createdAt: string;
    /**
     * The date and time the API key was last updated
     */
    updatedAt: string;
    /**
     * The user who created the API key
     */
    createdBy: string;
    /**
     * The user who created the API key
     */
    createdByUser?: UserRelationDto | null;
    /**
     * The user who last updated the API key
     */
    updatedBy: string;
    /**
     * The user who last updated the API key
     */
    updatedByUser?: UserRelationDto | null;
};

export type CreateApiKeyDto = {
    /**
     * The name of the API key
     */
    name: string;
    /**
     * The description of the API key
     */
    description?: string | null;
    /**
     * Whether the API key is enabled
     */
    enabled: boolean;
    /**
     * The resources that the API key is associated with
     */
    resources: Array<string>;
    /**
     * The labels that the API key is associated with
     */
    labels?: Array<string> | null;
    /**
     * Whether capacity is enforced for requests to the API key
     */
    enforceCapacity: boolean;
    /**
     * The capacities of the API key (JSON array)
     */
    capacity?: Array<CapacityEntity> | null;
};

export type CreatedApiKeyDto = {
    /**
     * The unique identifier for the API key (UUID)
     */
    apiKeyId: string;
    /**
     * The workspace that the API key is associated with
     */
    workspaceId: string;
    /**
     * The environment that the API key is associated with
     */
    environmentId: string;
    /**
     * The name of the API key
     */
    name: string;
    /**
     * The description of the API key
     */
    description?: string | null;
    /**
     * Whether the API key is enabled
     */
    enabled: boolean;
    /**
     * The resources that the API key is associated with
     */
    resources: Array<string>;
    /**
     * The labels that the API key is associated with
     */
    labels?: Array<string> | null;
    /**
     * Whether capacity is enforced for requests to the API key
     */
    enforceCapacity: boolean;
    /**
     * The capacities of the API key (JSON array)
     */
    capacity?: Array<CapacityEntity> | null;
    /**
     * The masked key of the API key
     */
    maskedKey: string;
    /**
     * The date and time the API key was created
     */
    createdAt: string;
    /**
     * The date and time the API key was last updated
     */
    updatedAt: string;
    /**
     * The user who created the API key
     */
    createdBy: string;
    /**
     * The user who created the API key
     */
    createdByUser?: UserRelationDto | null;
    /**
     * The user who last updated the API key
     */
    updatedBy: string;
    /**
     * The user who last updated the API key
     */
    updatedByUser?: UserRelationDto | null;
    /**
     * The full API key value, this is only returned once during creation
     */
    apiKeyValue: string;
};

export type UpdateApiKeyDto = {
    /**
     * The name of the API key
     */
    name?: string;
    /**
     * The description of the API key
     */
    description?: string | null;
    /**
     * Whether the API key is enabled
     */
    enabled?: boolean;
    /**
     * The resources that the API key is associated with
     */
    resources?: Array<string>;
    /**
     * The labels that the API key is associated with
     */
    labels?: Array<string> | null;
    /**
     * Whether capacity is enforced for requests to the API key
     */
    enforceCapacity?: boolean;
    /**
     * The capacities of the API key (JSON array)
     */
    capacity?: Array<CapacityEntity> | null;
};

export type MetricDto = {
    /**
     * The error rate of the metric
     */
    errorRate: number;
    /**
     * The total number of successful requests in the requested window
     */
    totalSuccess: number;
    /**
     * The total number of failed requests in the requested window
     */
    totalFailed: number;
    /**
     * The total number of requests in the requested window
     */
    totalRequests: number;
};

export type CompletionAuditFallbackEventEntity = {
    /**
     * The timestamp of the Audit event
     */
    timestamp: string;
    /**
     * The event type of the Audit event
     */
    type: 'fallback';
    /**
     * The data of the Audit event
     */
    data: {
        [key: string]: unknown;
    };
};

/**
 * The event type of the Audit event
 */
export enum CompletionAuditEventType {
    FALLBACK = 'FALLBACK',
    ROUTING = 'ROUTING'
}

export type CompletionAuditRoutingEventEntity = {
    /**
     * The timestamp of the Audit event
     */
    timestamp: string;
    /**
     * The event type of the Audit event
     */
    type: CompletionAuditEventType;
    /**
     * The data of the Audit event
     */
    data: {
        [key: string]: unknown;
    };
};

export enum CompletionAuditType {
    COMPLETION = 'COMPLETION',
    COMPLETION_BATCH = 'COMPLETION_BATCH'
}

export type CompletionAuditEntity = {
    /**
     * The unique identifier for the completion audit event (UUID)
     */
    id: string;
    /**
     * The timestamp of the completion audit event
     */
    timestamp: string;
    /**
     * The workspace that the completion audit event is associated with
     */
    workspaceId: string;
    /**
     * The environment that the completion audit event is associated with
     */
    environmentId: string;
    /**
     * The AI connection that the completion audit event is associated with
     */
    connectionId?: string | null;
    /**
     * The type of the completion audit event
     */
    type: CompletionAuditType;
    /**
     * The status code of the completion audit event
     */
    statusCode: number;
    /**
     * The duration of the completion audit event in milliseconds
     */
    duration: number;
    /**
     * The request ID of the completion audit event
     */
    requestId: string;
    /**
     * The events of the completion audit event (JSON array)
     */
    events?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * The batch ID of the completion audit event (if applicable)
     */
    batchId?: string | null;
    /**
     * The correlation ID for correlating logs and events (if applicable)
     */
    correlationId?: string | null;
    /**
     * The associated resource of the completion audit event (if applicable)
     */
    resource?: string | null;
    /**
     * The model involved in the completion audit event (if applicable)
     */
    model?: string | null;
    /**
     * The source IP address associated with the completion audit event (if applicable)
     */
    sourceIp?: string | null;
    /**
     * The error message if the completion audit event resulted in an error
     */
    errorMessage?: string | null;
    /**
     * The failure reason if the completion audit event failed
     */
    failureReason?: string | null;
    /**
     * API Key ID related to the completion audit event (if applicable)
     */
    apiKeyId?: string | null;
    /**
     * Additional data associated with the completion audit event (JSON object, if any)
     */
    data?: {
        [key: string]: unknown;
    } | null;
};

/**
 * Operator for the filter
 */
export enum CompletionUsageDimensionOperator {
    EQ = 'eq',
    NEQ = 'neq',
    IN = 'in',
    NIN = 'nin',
    GT = 'gt',
    GTE = 'gte',
    LT = 'lt',
    LTE = 'lte'
}

export type CompletionUsageDimensionFilterDto = {
    /**
     * Operator for the filter
     */
    operator: CompletionUsageDimensionOperator;
    /**
     * Value or values to compare against
     */
    value: string | Array<string>;
};

/**
 * Granularity unit for aggregation (time bucket size)
 */
export enum GranularityUnit {
    SECOND = 'second',
    SECOND_5 = 'second_5',
    SECOND_10 = 'second_10',
    SECOND_15 = 'second_15',
    SECOND_30 = 'second_30',
    MINUTE = 'minute',
    HOUR = 'hour',
    DAY = 'day',
    WEEK = 'week',
    MONTH = 'month',
    YEAR = 'year'
}

/**
 * Dimensions to group results by
 */
export enum CompletionDimensions {
    WORKSPACE_ID = 'workspaceId',
    ENVIRONMENT_ID = 'environmentId',
    CONNECTION_ID = 'connectionId',
    RESOURCE = 'resource',
    PROVIDER = 'provider',
    MODEL = 'model',
    REQUEST_ID = 'requestId',
    MESSAGE_ID = 'messageId',
    FAILURE_REASON = 'failureReason',
    STATUS_CODE = 'statusCode',
    CORRELATION_ID = 'correlationId',
    API_KEY_ID = 'apiKeyId',
    SOURCE_IP = 'sourceIp'
}

export type CompletionUsageQueryDateRangeDto = {
    /**
     * Start date (inclusive) of the date range for the query
     */
    start: string;
    /**
     * End date (exclusive) of the date range for the query
     */
    end: string;
};

export type CompletionUsageQueryFilterDto = {
    /**
     * Date range to filter the usage data
     */
    dateRange: CompletionUsageQueryDateRangeDto;
    /**
     * Dimensions and their filters
     */
    dimensions: {
        workspaceId?: CompletionUsageDimensionFilterDto;
        environmentId?: CompletionUsageDimensionFilterDto;
        connectionId?: CompletionUsageDimensionFilterDto;
        resource?: CompletionUsageDimensionFilterDto;
        provider?: CompletionUsageDimensionFilterDto;
        model?: CompletionUsageDimensionFilterDto;
        requestId?: CompletionUsageDimensionFilterDto;
        messageId?: CompletionUsageDimensionFilterDto;
        failureReason?: CompletionUsageDimensionFilterDto;
        statusCode?: CompletionUsageDimensionFilterDto;
        correlationId?: CompletionUsageDimensionFilterDto;
        apiKeyId?: CompletionUsageDimensionFilterDto;
        sourceIp?: CompletionUsageDimensionFilterDto;
    };
};

export type CompletionUsageQueryDto = {
    /**
     * Granularity unit for aggregation (time bucket size)
     */
    granularity: GranularityUnit;
    /**
     * Time zone to use for the query (defaults to UTC)
     */
    timeZone?: string | null;
    /**
     * Metrics and their aggregation types
     */
    agg: {
        promptTokens?: 'sum' | 'avg' | 'min' | 'max' | 'p99' | 'p95' | 'p90';
        completionTokens?: 'sum' | 'avg' | 'min' | 'max' | 'p99' | 'p95' | 'p90';
        totalTokens?: 'sum' | 'avg' | 'min' | 'max' | 'p99' | 'p95' | 'p90';
        tokensPerSecond?: 'sum' | 'avg' | 'min' | 'max' | 'p99' | 'p95' | 'p90';
        timeToFirstToken?: 'sum' | 'avg' | 'min' | 'max' | 'p99' | 'p95' | 'p90';
        requestCount?: 'sum' | 'avg' | 'min' | 'max' | 'p99' | 'p95' | 'p90';
        errorCount?: 'sum' | 'avg' | 'min' | 'max' | 'p99' | 'p95' | 'p90';
        successCount?: 'sum' | 'avg' | 'min' | 'max' | 'p99' | 'p95' | 'p90';
        requestDuration?: 'sum' | 'avg' | 'min' | 'max' | 'p99' | 'p95' | 'p90';
        providerDuration?: 'sum' | 'avg' | 'min' | 'max' | 'p99' | 'p95' | 'p90';
        gateDuration?: 'sum' | 'avg' | 'min' | 'max' | 'p99' | 'p95' | 'p90';
        routingDuration?: 'sum' | 'avg' | 'min' | 'max' | 'p99' | 'p95' | 'p90';
    };
    /**
     * Dimensions to group results by
     */
    dimensions: Array<CompletionDimensions>;
    /**
     * Maximum number of records to return
     */
    limit: number;
    /**
     * Filter for the query
     */
    filter: CompletionUsageQueryFilterDto;
    /**
     * Order by the query
     */
    orderBy?: {
        workspaceId?: 'asc' | 'desc';
        environmentId?: 'asc' | 'desc';
        connectionId?: 'asc' | 'desc';
        resource?: 'asc' | 'desc';
        provider?: 'asc' | 'desc';
        model?: 'asc' | 'desc';
        requestId?: 'asc' | 'desc';
        messageId?: 'asc' | 'desc';
        failureReason?: 'asc' | 'desc';
        statusCode?: 'asc' | 'desc';
        correlationId?: 'asc' | 'desc';
        apiKeyId?: 'asc' | 'desc';
        sourceIp?: 'asc' | 'desc';
    } | null;
};

export type CompletionUsageQueryResultDto = {
    /**
     * Time bucket truncated to the granularity unit
     */
    time: string;
    /**
     * Completion input tokens
     */
    promptTokens?: number | null;
    /**
     * Completion output tokens
     */
    completionTokens?: number | null;
    /**
     * Total number of tokens
     */
    totalTokens?: number | null;
    /**
     * Tokens generated per second
     */
    tokensPerSecond?: number | null;
    /**
     * Time to generate the first token (milliseconds)
     */
    timeToFirstToken?: number | null;
    /**
     * Total number of requests
     */
    requestCount?: number | null;
    /**
     * Total number of errors
     */
    errorCount?: number | null;
    /**
     * Total number of successes
     */
    successCount?: number | null;
    /**
     * Total request duration (milliseconds)
     */
    requestDuration?: number | null;
    /**
     * Time spent in the AI provider API (milliseconds)
     */
    providerDuration?: number | null;
    /**
     * Time spent in the gate service (milliseconds)
     */
    gateDuration?: number | null;
    /**
     * Time spent in routing (milliseconds)
     */
    routingDuration?: number | null;
    /**
     * Workspace Identifier
     */
    workspaceId?: string | null;
    /**
     * Environment Identifier
     */
    environmentId?: string | null;
    /**
     * AI Connection Identifier
     */
    connectionId?: string | null;
    /**
     * AI Resource Identifier
     */
    resource?: string | null;
    /**
     * Provider name
     */
    provider?: string | null;
    /**
     * Model name
     */
    model?: string | null;
    /**
     * Unique identifier for the request
     */
    requestId?: string | null;
    /**
     * Unique identifier for the message
     */
    messageId?: string | null;
    /**
     * Reason for failure, if applicable
     */
    failureReason?: string | null;
    /**
     * HTTP status code of the response
     */
    statusCode?: number | null;
    /**
     * Correlation ID for tracing requests
     */
    correlationId?: string | null;
    /**
     * API key identifier used for the request
     */
    apiKeyId?: string | null;
    /**
     * Source IP address of the request
     */
    sourceIp?: string | null;
};

export type CreateCompletionBatchItemDto = {
    /**
     * The name of the resource this item references
     */
    resource: string;
    /**
     * The completion request payload (openai chat completion request payload)
     */
    request: {
        [key: string]: unknown;
    };
};

/**
 * The type of the batch request
 */
export enum CompletionBatchRequestType {
    SYNC = 'SYNC',
    ASYNC = 'ASYNC'
}

export type CreateCompletionBatchDto = {
    /**
     * The capacities of the batch request
     */
    capacity: Array<CapacityEntity>;
    /**
     * The items to create in the batch
     */
    items: Array<CreateCompletionBatchItemDto>;
    /**
     * The type of the batch request
     */
    type: CompletionBatchRequestType;
};

/**
 * The events to send the callback for
 */
export enum CompletionBatchCallbackEvent {
    BATCH_UPDATE = 'batch_update',
    ITEM_UPDATE = 'item_update',
    ALL = 'all'
}

export type CompletionBatchCallbackOptionsDto = {
    /**
     * The URL to send the callback to
     */
    url: string;
    /**
     * The headers to send with the callback
     */
    headers?: {
        [key: string]: string;
    } | null;
    /**
     * The events to send the callback for
     */
    events: CompletionBatchCallbackEvent;
};

export type CreateCompletionCallbackBatchDto = {
    /**
     * The capacities of the batch request
     */
    capacity: Array<CapacityEntity>;
    /**
     * The items to create in the batch
     */
    items: Array<CreateCompletionBatchItemDto>;
    /**
     * The type of the batch request
     */
    type: CompletionBatchRequestType;
    /**
     * The callback options for the batch request
     */
    callbackOptions: CompletionBatchCallbackOptionsDto;
};

/**
 * The status of the batch request
 */
export enum CompletionBatchRequestStatus {
    CANCELLED = 'CANCELLED',
    COMPLETED = 'COMPLETED',
    FAILED = 'FAILED',
    PENDING = 'PENDING',
    RUNNING = 'RUNNING'
}

export type ApiKeyRelationDto = {
    /**
     * The unique identifier for the API key (UUID)
     */
    apiKeyId: string;
    /**
     * The workspace that the API key is associated with
     */
    workspaceId: string;
    /**
     * The environment that the API key is associated with
     */
    environmentId: string;
    /**
     * The name of the API key
     */
    name: string;
    /**
     * The description of the API key
     */
    description?: string | null;
    /**
     * Whether the API key is enabled
     */
    enabled: boolean;
    /**
     * The resources that the API key is associated with
     */
    resources: Array<string>;
    /**
     * The labels that the API key is associated with
     */
    labels?: Array<string> | null;
    /**
     * Whether capacity is enforced for requests to the API key
     */
    enforceCapacity: boolean;
    /**
     * The capacities of the API key (JSON array)
     */
    capacity?: Array<CapacityEntity> | null;
    /**
     * The masked key of the API key
     */
    maskedKey: string;
    /**
     * The user who created the API key
     */
    createdBy: string;
    /**
     * The user who created the API key
     */
    createdByUser?: UserRelationDto | null;
    /**
     * The user who last updated the API key
     */
    updatedBy: string;
    /**
     * The user who last updated the API key
     */
    updatedByUser?: UserRelationDto | null;
    /**
     * The date and time the API key was created
     */
    createdAt: string;
    /**
     * The date and time the API key was last updated
     */
    updatedAt: string;
};

export type CompletionBatchItemRelationDto = {
    /**
     * The unique identifier for the workspace (UUID)
     */
    workspaceId: string;
    /**
     * The unique identifier for the environment (UUID)
     */
    environmentId: string;
    /**
     * The unique identifier for the batch (UUID)
     */
    batchId: string;
    /**
     * The unique identifier for the batch item (UUID)
     */
    itemId: string;
    /**
     * The name of the resource this item references
     */
    resource: string;
    /**
     * The status of the batch item
     */
    status: CompletionBatchRequestStatus;
    /**
     * The completion request payload (openai chat completion request payload)
     */
    request: {
        [key: string]: unknown;
    };
    /**
     * The response for the batch item (if completed) (openai chat completion response)
     */
    response?: {
        [key: string]: unknown;
    } | null;
    /**
     * The estimated number of prompt tokens for the batch item
     */
    estimatedPromptTokens: number;
    /**
     * Number of completion tokens used
     */
    completionTokens: number;
    /**
     * Number of prompt tokens used
     */
    promptTokens: number;
    /**
     * Total number of tokens used
     */
    totalTokens: number;
    /**
     * The error message if the batch item failed
     */
    errorMessage?: string | null;
    /**
     * The number of times this item has been retried
     */
    retryCount: number;
    /**
     * The date and time the batch item was created
     */
    createdAt: string;
    /**
     * The date and time the batch item was completed
     */
    completedAt?: string | null;
};

export type CompletionBatchDto = {
    /**
     * The unique identifier for the workspace (UUID)
     */
    workspaceId: string;
    /**
     * The unique identifier for the environment (UUID)
     */
    environmentId: string;
    /**
     * The timestamp of the batch request
     */
    timestamp: string;
    /**
     * The unique identifier for the batch request (UUID)
     */
    batchId: string;
    /**
     * The type of the batch request
     */
    type: CompletionBatchRequestType;
    /**
     * The callback options for the batch request
     */
    callbackOptions?: CompletionBatchCallbackOptionsDto | null;
    /**
     * The capacities of the batch request
     */
    capacity?: Array<CapacityEntity> | null;
    /**
     * The number of completed items in the batch request
     */
    completed: number;
    /**
     * The date and time the batch request was completed
     */
    completedAt?: string | null;
    /**
     * The number of failed items in the batch request
     */
    failed: number;
    /**
     * The number of pending items in the batch request
     */
    pending: number;
    /**
     * The number of running items in the batch request
     */
    running: number;
    /**
     * The status of the batch request
     */
    status: CompletionBatchRequestStatus;
    /**
     * The total estimated number of prompt tokens in the batch request
     */
    totalEstimatedPromptTokens: number;
    /**
     * The total number of prompt tokens in the batch request
     */
    totalPromptTokens: number;
    /**
     * The total number of completion tokens in the batch request
     */
    totalCompletionTokens: number;
    /**
     * The total number of items in the batch request
     */
    totalItems: number;
    /**
     * The error message of the batch request
     */
    errorMessage?: string | null;
    /**
     * The date and time the batch request was last updated
     */
    updatedAt: string;
    /**
     * The date and time the batch request was created
     */
    createdAt: string;
    /**
     * The unique identifier for the API key that created the batch request
     */
    createdByApiKeyId?: string | null;
    /**
     * The API key that created the batch request
     */
    createdByApiKey?: ApiKeyRelationDto | null;
    /**
     * The unique identifier for the user that created the batch request
     */
    createdByUserId?: string | null;
    /**
     * The user that created the batch request
     */
    createdByUser?: UserRelationDto | null;
    /**
     * The items in the batch
     */
    items?: Array<CompletionBatchItemRelationDto> | null;
    /**
     * The completed percentage of the batch request
     */
    completedPercentage?: number | null;
};

export type CompletionBatchItemEntity = {
    /**
     * The unique identifier for the workspace (UUID)
     */
    workspaceId: string;
    /**
     * The unique identifier for the environment (UUID)
     */
    environmentId: string;
    /**
     * The unique identifier for the batch (UUID)
     */
    batchId: string;
    /**
     * The unique identifier for the batch item (UUID)
     */
    itemId: string;
    /**
     * The name of the resource this item references
     */
    resource: string;
    /**
     * The status of the batch item
     */
    status: CompletionBatchRequestStatus;
    /**
     * The completion request payload (openai chat completion request payload)
     */
    request: {
        [key: string]: unknown;
    };
    /**
     * The response for the batch item (if completed) (openai chat completion response)
     */
    response?: {
        [key: string]: unknown;
    } | null;
    /**
     * The timestamp when the item was completed
     */
    completedAt?: string | null;
    /**
     * The estimated number of prompt tokens for the batch item
     */
    estimatedPromptTokens: number;
    /**
     * Number of completion tokens used
     */
    completionTokens: number;
    /**
     * Number of prompt tokens used
     */
    promptTokens: number;
    /**
     * Total number of tokens used
     */
    totalTokens: number;
    /**
     * The error message if the batch item failed
     */
    errorMessage?: string | null;
    /**
     * The number of times this item has been retried
     */
    retryCount: number;
    /**
     * The timestamp when the item was created
     */
    createdAt: string;
};

export type HealthcheckControllerHealthcheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthcheck';
};

export type HealthcheckControllerHealthcheckResponses = {
    /**
     * Healthcheck endpoint
     */
    200: HealthcheckResponseDto;
};

export type HealthcheckControllerHealthcheckResponse = HealthcheckControllerHealthcheckResponses[keyof HealthcheckControllerHealthcheckResponses];

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/user';
};

export type GetUsersErrors = {
    /**
     * Server Error
     */
    500: ServiceError;
};

export type GetUsersError = GetUsersErrors[keyof GetUsersErrors];

export type GetUsersResponses = {
    /**
     * List all users
     */
    200: Array<UserEntity>;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type OidcInteractionControllerShowInteractionData = {
    body?: never;
    path: {
        uid: string;
    };
    query?: never;
    url: '/interaction/{uid}';
};

export type OidcInteractionControllerShowInteractionResponses = {
    /**
     * Show Login/Consent Interaction HTML page
     */
    200: unknown;
};

export type OidcInteractionControllerLoginData = {
    body: LoginDto;
    path: {
        uid: string;
    };
    query?: never;
    url: '/interaction/{uid}/login';
};

export type OidcInteractionControllerLoginResponses = {
    /**
     * Handle login submission
     */
    200: unknown;
};

export type OidcInteractionControllerConsentData = {
    body: ConsentDto;
    path: {
        uid: string;
    };
    query?: never;
    url: '/interaction/{uid}/consent';
};

export type OidcInteractionControllerConsentResponses = {
    /**
     * Handle consent submission
     */
    200: unknown;
};

export type OidcInteractionControllerFederatedCallbackData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/interaction/federated/callback';
};

export type OidcInteractionControllerFederatedCallbackResponses = {
    /**
     * Static federated callback that redirects to the UID interaction federated page
     */
    200: unknown;
};

export type OidcInteractionControllerFederatedInteractionData = {
    body?: never;
    path: {
        uid: string;
    };
    query?: never;
    url: '/interaction/{uid}/federated';
};

export type OidcInteractionControllerFederatedInteractionResponses = {
    /**
     * Continues with the federated login process
     */
    200: unknown;
};

export type GetWorkspacesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Whether to include users in the response
         */
        includesUsers?: boolean;
        /**
         * Whether to include environments in the response
         */
        includesEnvironments?: boolean;
    };
    url: '/v1/workspace';
};

export type GetWorkspacesErrors = {
    /**
     * Server Error
     */
    500: ServiceError;
};

export type GetWorkspacesError = GetWorkspacesErrors[keyof GetWorkspacesErrors];

export type GetWorkspacesResponses = {
    /**
     * List all workspaces that the user is a member of
     */
    200: Array<WorkspaceEntity>;
};

export type GetWorkspacesResponse = GetWorkspacesResponses[keyof GetWorkspacesResponses];

export type CreateWorkspaceData = {
    body: CreateWorkspaceDto;
    path?: never;
    query?: never;
    url: '/v1/workspace';
};

export type CreateWorkspaceErrors = {
    /**
     * Server Error
     */
    500: ServiceError;
};

export type CreateWorkspaceError = CreateWorkspaceErrors[keyof CreateWorkspaceErrors];

export type CreateWorkspaceResponses = {
    /**
     * Create a new workspace
     */
    200: WorkspaceEntity;
};

export type CreateWorkspaceResponse = CreateWorkspaceResponses[keyof CreateWorkspaceResponses];

export type DeleteWorkspaceData = {
    body?: never;
    path: {
        /**
         * The ID of the workspace
         */
        workspaceId: string;
    };
    query?: never;
    url: '/v1/workspace/{workspaceId}';
};

export type DeleteWorkspaceErrors = {
    /**
     * Server Error
     */
    500: ServiceError;
};

export type DeleteWorkspaceError = DeleteWorkspaceErrors[keyof DeleteWorkspaceErrors];

export type DeleteWorkspaceResponses = {
    /**
     * Delete a workspace
     */
    200: unknown;
};

export type GetWorkspaceByIdData = {
    body?: never;
    path: {
        /**
         * The ID of the workspace
         */
        workspaceId: string;
    };
    query?: {
        /**
         * Whether to include users in the response
         */
        includesUsers?: boolean;
    };
    url: '/v1/workspace/{workspaceId}';
};

export type GetWorkspaceByIdErrors = {
    /**
     * Server Error
     */
    500: ServiceError;
};

export type GetWorkspaceByIdError = GetWorkspaceByIdErrors[keyof GetWorkspaceByIdErrors];

export type GetWorkspaceByIdResponses = {
    /**
     * Get a workspace by ID
     */
    200: WorkspaceEntity;
};

export type GetWorkspaceByIdResponse = GetWorkspaceByIdResponses[keyof GetWorkspaceByIdResponses];

export type UpdateWorkspaceData = {
    body: UpdateWorkspaceDto;
    path: {
        /**
         * The ID of the workspace
         */
        workspaceId: string;
    };
    query?: never;
    url: '/v1/workspace/{workspaceId}';
};

export type UpdateWorkspaceErrors = {
    /**
     * Server Error
     */
    500: ServiceError;
};

export type UpdateWorkspaceError = UpdateWorkspaceErrors[keyof UpdateWorkspaceErrors];

export type UpdateWorkspaceResponses = {
    /**
     * Update a workspace
     */
    200: WorkspaceEntity;
};

export type UpdateWorkspaceResponse = UpdateWorkspaceResponses[keyof UpdateWorkspaceResponses];

export type GetEnvironmentsData = {
    body?: never;
    path: {
        /**
         * The ID of the workspace
         */
        workspaceId: string;
    };
    query?: {
        /**
         * Whether to include users in the response
         */
        includesUsers?: boolean;
    };
    url: '/v1/environment/{workspaceId}';
};

export type GetEnvironmentsErrors = {
    /**
     * Server Error
     */
    500: ServiceError;
};

export type GetEnvironmentsError = GetEnvironmentsErrors[keyof GetEnvironmentsErrors];

export type GetEnvironmentsResponses = {
    /**
     * List all environments that the user is a member of
     */
    200: Array<EnvironmentEntity>;
};

export type GetEnvironmentsResponse = GetEnvironmentsResponses[keyof GetEnvironmentsResponses];

export type CreateEnvironmentData = {
    body: CreateEnvironmentDto;
    path: {
        /**
         * The ID of the workspace
         */
        workspaceId: string;
    };
    query?: never;
    url: '/v1/environment/{workspaceId}';
};

export type CreateEnvironmentErrors = {
    /**
     * Server Error
     */
    500: ServiceError;
};

export type CreateEnvironmentError = CreateEnvironmentErrors[keyof CreateEnvironmentErrors];

export type CreateEnvironmentResponses = {
    /**
     * Create a new environment
     */
    200: EnvironmentEntity;
};

export type CreateEnvironmentResponse = CreateEnvironmentResponses[keyof CreateEnvironmentResponses];

export type DeleteEnvironmentData = {
    body?: never;
    path: {
        /**
         * The ID of the workspace
         */
        workspaceId: string;
        environmentId: string;
    };
    query?: never;
    url: '/v1/environment/{workspaceId}/{environmentId}';
};

export type DeleteEnvironmentErrors = {
    /**
     * Server Error
     */
    500: ServiceError;
};

export type DeleteEnvironmentError = DeleteEnvironmentErrors[keyof DeleteEnvironmentErrors];

export type DeleteEnvironmentResponses = {
    /**
     * Delete an environment
     */
    200: unknown;
};

export type GetEnvironmentByIdData = {
    body?: never;
    path: {
        /**
         * The ID of the workspace
         */
        workspaceId: string;
        /**
         * The ID of the environment
         */
        environmentId: string;
    };
    query?: {
        /**
         * Whether to include users in the response
         */
        includesUsers?: boolean;
    };
    url: '/v1/environment/{workspaceId}/{environmentId}';
};

export type GetEnvironmentByIdErrors = {
    /**
     * Server Error
     */
    500: ServiceError;
};

export type GetEnvironmentByIdError = GetEnvironmentByIdErrors[keyof GetEnvironmentByIdErrors];

export type GetEnvironmentByIdResponses = {
    /**
     * Get an environment by ID
     */
    200: EnvironmentEntity;
};

export type GetEnvironmentByIdResponse = GetEnvironmentByIdResponses[keyof GetEnvironmentByIdResponses];

export type UpdateEnvironmentData = {
    body: UpdateEnvironmentDto;
    path: {
        /**
         * The ID of the workspace
         */
        workspaceId: string;
        /**
         * The ID of the environment
         */
        environmentId: string;
    };
    query?: never;
    url: '/v1/environment/{workspaceId}/{environmentId}';
};

export type UpdateEnvironmentErrors = {
    /**
     * Server Error
     */
    500: ServiceError;
};

export type UpdateEnvironmentError = UpdateEnvironmentErrors[keyof UpdateEnvironmentErrors];

export type UpdateEnvironmentResponses = {
    /**
     * Update an environment
     */
    200: EnvironmentEntity;
};

export type UpdateEnvironmentResponse = UpdateEnvironmentResponses[keyof UpdateEnvironmentResponses];

export type GetAiConnectionsData = {
    body?: never;
    path: {
        /**
         * The ID of the workspace
         */
        workspaceId: string;
        /**
         * The ID of the environment
         */
        environmentId: string;
    };
    query?: {
        /**
         * Whether to include users in the response
         */
        includesUsers?: boolean;
    };
    url: '/v1/ai-connection/{workspaceId}/{environmentId}';
};

export type GetAiConnectionsErrors = {
    /**
     * Server Error
     */
    500: ServiceError;
};

export type GetAiConnectionsError = GetAiConnectionsErrors[keyof GetAiConnectionsErrors];

export type GetAiConnectionsResponses = {
    /**
     * List all AI connections associated with an environment
     */
    200: Array<AiConnectionEntity>;
};

export type GetAiConnectionsResponse = GetAiConnectionsResponses[keyof GetAiConnectionsResponses];

export type CreateAiConnectionData = {
    body: CreateAiConnectionDto;
    path: {
        /**
         * The ID of the workspace
         */
        workspaceId: string;
        /**
         * The ID of the environment
         */
        environmentId: string;
    };
    query?: never;
    url: '/v1/ai-connection/{workspaceId}/{environmentId}';
};

export type CreateAiConnectionErrors = {
    /**
     * Server Error
     */
    500: ServiceError;
};

export type CreateAiConnectionError = CreateAiConnectionErrors[keyof CreateAiConnectionErrors];

export type CreateAiConnectionResponses = {
    /**
     * Create a new AI connection
     */
    200: AiConnectionEntity;
};

export type CreateAiConnectionResponse = CreateAiConnectionResponses[keyof CreateAiConnectionResponses];

export type DeleteAiConnectionData = {
    body?: never;
    path: {
        /**
         * The ID of the workspace
         */
        workspaceId: string;
        environmentId: string;
        connectionId: string;
    };
    query?: never;
    url: '/v1/ai-connection/{workspaceId}/{environmentId}/{connectionId}';
};

export type DeleteAiConnectionErrors = {
    /**
     * Server Error
     */
    500: ServiceError;
};

export type DeleteAiConnectionError = DeleteAiConnectionErrors[keyof DeleteAiConnectionErrors];

export type DeleteAiConnectionResponses = {
    /**
     * Delete an AI connection
     */
    200: unknown;
};

export type GetAiConnectionByIdData = {
    body?: never;
    path: {
        /**
         * The ID of the workspace
         */
        workspaceId: string;
        /**
         * The ID of the environment
         */
        environmentId: string;
        /**
         * The ID of the AI connection
         */
        connectionId: string;
    };
    query?: {
        /**
         * Whether to include users in the response
         */
        includesUsers?: boolean;
    };
    url: '/v1/ai-connection/{workspaceId}/{environmentId}/{connectionId}';
};

export type GetAiConnectionByIdErrors = {
    /**
     * Server Error
     */
    500: ServiceError;
};

export type GetAiConnectionByIdError = GetAiConnectionByIdErrors[keyof GetAiConnectionByIdErrors];

export type GetAiConnectionByIdResponses = {
    /**
     * Get an AI connection by ID
     */
    200: AiConnectionEntity;
};

export type GetAiConnectionByIdResponse = GetAiConnectionByIdResponses[keyof GetAiConnectionByIdResponses];

export type UpdateAiConnectionData = {
    body: UpdateAiConnectionDto;
    path: {
        /**
         * The ID of the workspace
         */
        workspaceId: string;
        /**
         * The ID of the environment
         */
        environmentId: string;
        connectionId: string;
    };
    query?: never;
    url: '/v1/ai-connection/{workspaceId}/{environmentId}/{connectionId}';
};

export type UpdateAiConnectionErrors = {
    /**
     * Server Error
     */
    500: ServiceError;
};

export type UpdateAiConnectionError = UpdateAiConnectionErrors[keyof UpdateAiConnectionErrors];

export type UpdateAiConnectionResponses = {
    /**
     * Update an AI connection
     */
    200: AiConnectionEntity;
};

export type UpdateAiConnectionResponse = UpdateAiConnectionResponses[keyof UpdateAiConnectionResponses];

export type GetAiProvidersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/ai-provider';
};

export type GetAiProvidersErrors = {
    /**
     * Server Error
     */
    500: ServiceError;
};

export type GetAiProvidersError = GetAiProvidersErrors[keyof GetAiProvidersErrors];

export type GetAiProvidersResponses = {
    /**
     * List all AI providers
     */
    200: Array<AiProviderDto>;
};

export type GetAiProvidersResponse = GetAiProvidersResponses[keyof GetAiProvidersResponses];

export type GetAiResourcesData = {
    body?: never;
    path: {
        /**
         * The ID of the workspace
         */
        workspaceId: string;
        /**
         * The ID of the environment
         */
        environmentId: string;
    };
    query?: {
        /**
         * Whether to include users in the response
         */
        includesUsers?: boolean;
        /**
         * The connection ID to list AI resources for
         */
        connectionId?: string;
    };
    url: '/v1/ai-resource/{workspaceId}/{environmentId}';
};

export type GetAiResourcesErrors = {
    /**
     * Server Error
     */
    500: ServiceError;
};

export type GetAiResourcesError = GetAiResourcesErrors[keyof GetAiResourcesErrors];

export type GetAiResourcesResponses = {
    /**
     * List all AI resources associated with an environment
     */
    200: Array<AiResourceEntity>;
};

export type GetAiResourcesResponse = GetAiResourcesResponses[keyof GetAiResourcesResponses];

export type CreateAiResourceData = {
    body: CreateAiResourceDto;
    path: {
        /**
         * The ID of the workspace
         */
        workspaceId: string;
        /**
         * The ID of the environment
         */
        environmentId: string;
    };
    query?: never;
    url: '/v1/ai-resource/{workspaceId}/{environmentId}';
};

export type CreateAiResourceErrors = {
    /**
     * Server Error
     */
    500: ServiceError;
};

export type CreateAiResourceError = CreateAiResourceErrors[keyof CreateAiResourceErrors];

export type CreateAiResourceResponses = {
    /**
     * Create a new AI resource
     */
    200: AiResourceEntity;
};

export type CreateAiResourceResponse = CreateAiResourceResponses[keyof CreateAiResourceResponses];

export type DeleteAiResourceData = {
    body?: never;
    path: {
        /**
         * The ID of the workspace
         */
        workspaceId: string;
        environmentId: string;
        resource: string;
    };
    query?: never;
    url: '/v1/ai-resource/{workspaceId}/{environmentId}/{resource}';
};

export type DeleteAiResourceErrors = {
    /**
     * Server Error
     */
    500: ServiceError;
};

export type DeleteAiResourceError = DeleteAiResourceErrors[keyof DeleteAiResourceErrors];

export type DeleteAiResourceResponses = {
    /**
     * Delete an AI resource
     */
    200: unknown;
};

export type GetAiResourceByIdData = {
    body?: never;
    path: {
        /**
         * The ID of the workspace
         */
        workspaceId: string;
        /**
         * The ID of the environment
         */
        environmentId: string;
        /**
         * The unique identifier of the AI resource
         */
        resource: string;
    };
    query?: {
        /**
         * Whether to include users in the response
         */
        includesUsers?: boolean;
    };
    url: '/v1/ai-resource/{workspaceId}/{environmentId}/{resource}';
};

export type GetAiResourceByIdErrors = {
    /**
     * Server Error
     */
    500: ServiceError;
};

export type GetAiResourceByIdError = GetAiResourceByIdErrors[keyof GetAiResourceByIdErrors];

export type GetAiResourceByIdResponses = {
    /**
     * Get an AI resource by ID
     */
    200: AiResourceEntity;
};

export type GetAiResourceByIdResponse = GetAiResourceByIdResponses[keyof GetAiResourceByIdResponses];

export type UpdateAiResourceData = {
    body: UpdateAiResourceDto;
    path: {
        /**
         * The ID of the workspace
         */
        workspaceId: string;
        /**
         * The ID of the environment
         */
        environmentId: string;
        resource: string;
    };
    query?: never;
    url: '/v1/ai-resource/{workspaceId}/{environmentId}/{resource}';
};

export type UpdateAiResourceErrors = {
    /**
     * Server Error
     */
    500: ServiceError;
};

export type UpdateAiResourceError = UpdateAiResourceErrors[keyof UpdateAiResourceErrors];

export type UpdateAiResourceResponses = {
    /**
     * Update an AI resource
     */
    200: AiResourceEntity;
};

export type UpdateAiResourceResponse = UpdateAiResourceResponses[keyof UpdateAiResourceResponses];

export type DeletePoolDefinitionData = {
    body?: never;
    path: {
        /**
         * The ID of the workspace
         */
        workspaceId: string;
        environmentId: string;
    };
    query?: never;
    url: '/v1/pool-definition/{workspaceId}/{environmentId}';
};

export type DeletePoolDefinitionErrors = {
    /**
     * Server Error
     */
    500: ServiceError;
};

export type DeletePoolDefinitionError = DeletePoolDefinitionErrors[keyof DeletePoolDefinitionErrors];

export type DeletePoolDefinitionResponses = {
    /**
     * Delete a pool definition
     */
    200: unknown;
};

export type GetPoolDefinitionData = {
    body?: never;
    path: {
        /**
         * The ID of the workspace
         */
        workspaceId: string;
        /**
         * The ID of the environment
         */
        environmentId: string;
    };
    query?: {
        /**
         * Whether to include users in the response
         */
        includesUsers?: boolean;
    };
    url: '/v1/pool-definition/{workspaceId}/{environmentId}';
};

export type GetPoolDefinitionErrors = {
    /**
     * Server Error
     */
    500: ServiceError;
};

export type GetPoolDefinitionError = GetPoolDefinitionErrors[keyof GetPoolDefinitionErrors];

export type GetPoolDefinitionResponses = {
    /**
     * Get a pool definition by workspace and environment
     */
    200: PoolDefinitionEntity;
};

export type GetPoolDefinitionResponse = GetPoolDefinitionResponses[keyof GetPoolDefinitionResponses];

export type UpdatePoolDefinitionData = {
    body: UpsertPoolDefinitionDto;
    path: {
        /**
         * The ID of the workspace
         */
        workspaceId: string;
        /**
         * The ID of the environment
         */
        environmentId: string;
    };
    query?: never;
    url: '/v1/pool-definition/{workspaceId}/{environmentId}';
};

export type UpdatePoolDefinitionErrors = {
    /**
     * Server Error
     */
    500: ServiceError;
};

export type UpdatePoolDefinitionError = UpdatePoolDefinitionErrors[keyof UpdatePoolDefinitionErrors];

export type UpdatePoolDefinitionResponses = {
    /**
     * Created/updated a pool definition
     */
    200: PoolDefinitionEntity;
};

export type UpdatePoolDefinitionResponse = UpdatePoolDefinitionResponses[keyof UpdatePoolDefinitionResponses];

export type GetApiKeysData = {
    body?: never;
    path: {
        /**
         * The ID of the workspace
         */
        workspaceId: string;
        /**
         * The ID of the environment
         */
        environmentId: string;
    };
    query?: {
        /**
         * Whether to include users in the response
         */
        includesUsers?: boolean;
    };
    url: '/v1/api-key/{workspaceId}/{environmentId}';
};

export type GetApiKeysErrors = {
    /**
     * Server Error
     */
    500: ServiceError;
};

export type GetApiKeysError = GetApiKeysErrors[keyof GetApiKeysErrors];

export type GetApiKeysResponses = {
    /**
     * List all API keys associated with an environment
     */
    200: Array<ApiKeyEntity>;
};

export type GetApiKeysResponse = GetApiKeysResponses[keyof GetApiKeysResponses];

export type CreateApiKeyData = {
    body: CreateApiKeyDto;
    path: {
        /**
         * The ID of the workspace
         */
        workspaceId: string;
        /**
         * The ID of the environment
         */
        environmentId: string;
    };
    query?: never;
    url: '/v1/api-key/{workspaceId}/{environmentId}';
};

export type CreateApiKeyErrors = {
    /**
     * Server Error
     */
    500: ServiceError;
};

export type CreateApiKeyError = CreateApiKeyErrors[keyof CreateApiKeyErrors];

export type CreateApiKeyResponses = {
    /**
     * Create a new API key
     */
    200: CreatedApiKeyDto;
};

export type CreateApiKeyResponse = CreateApiKeyResponses[keyof CreateApiKeyResponses];

export type DeleteApiKeyData = {
    body?: never;
    path: {
        /**
         * The ID of the workspace
         */
        workspaceId: string;
        environmentId: string;
        apiKeyId: string;
    };
    query?: never;
    url: '/v1/api-key/{workspaceId}/{environmentId}/{apiKeyId}';
};

export type DeleteApiKeyErrors = {
    /**
     * Server Error
     */
    500: ServiceError;
};

export type DeleteApiKeyError = DeleteApiKeyErrors[keyof DeleteApiKeyErrors];

export type DeleteApiKeyResponses = {
    /**
     * Delete an API key
     */
    200: unknown;
};

export type GetApiKeyByIdData = {
    body?: never;
    path: {
        /**
         * The ID of the workspace
         */
        workspaceId: string;
        /**
         * The ID of the environment
         */
        environmentId: string;
        /**
         * The unique identifier of the API key
         */
        apiKeyId: string;
    };
    query?: {
        /**
         * Whether to include users in the response
         */
        includesUsers?: boolean;
    };
    url: '/v1/api-key/{workspaceId}/{environmentId}/{apiKeyId}';
};

export type GetApiKeyByIdErrors = {
    /**
     * Server Error
     */
    500: ServiceError;
};

export type GetApiKeyByIdError = GetApiKeyByIdErrors[keyof GetApiKeyByIdErrors];

export type GetApiKeyByIdResponses = {
    /**
     * Get an API key by ID
     */
    200: ApiKeyEntity;
};

export type GetApiKeyByIdResponse = GetApiKeyByIdResponses[keyof GetApiKeyByIdResponses];

export type UpdateApiKeyData = {
    body: UpdateApiKeyDto;
    path: {
        /**
         * The ID of the workspace
         */
        workspaceId: string;
        /**
         * The ID of the environment
         */
        environmentId: string;
        apiKeyId: string;
    };
    query?: never;
    url: '/v1/api-key/{workspaceId}/{environmentId}/{apiKeyId}';
};

export type UpdateApiKeyErrors = {
    /**
     * Server Error
     */
    500: ServiceError;
};

export type UpdateApiKeyError = UpdateApiKeyErrors[keyof UpdateApiKeyErrors];

export type UpdateApiKeyResponses = {
    /**
     * Update an API key
     */
    200: ApiKeyEntity;
};

export type UpdateApiKeyResponse = UpdateApiKeyResponses[keyof UpdateApiKeyResponses];

export type CompletionData = {
    body?: {
        [key: string]: unknown;
    };
    path: {
        /**
         * The ID of the workspace
         */
        workspaceId: string;
        /**
         * The ID of the environment
         */
        environmentId: string;
        /**
         * The unique identifier of the AI resource
         */
        resource: string;
    };
    query?: never;
    url: '/v1/completion/{workspaceId}/{environmentId}/{resource}/chat/completions';
};

export type CompletionResponses = {
    201: unknown;
};

export type GetCompletionErrorRateData = {
    body?: never;
    path: {
        /**
         * The ID of the workspace
         */
        workspaceId: string;
        /**
         * The ID of the environment
         */
        environmentId: string;
        /**
         * The unique identifier of the AI resource
         */
        resource: string;
    };
    query: {
        aiConnectionId: string;
        model: string;
    };
    url: '/v1/completion-metric/{workspaceId}/{environmentId}/{resource}/error-rate';
};

export type GetCompletionErrorRateErrors = {
    /**
     * Server Error
     */
    500: ServiceError;
};

export type GetCompletionErrorRateError = GetCompletionErrorRateErrors[keyof GetCompletionErrorRateErrors];

export type GetCompletionErrorRateResponses = {
    /**
     * Get the error rate for an AI resource
     */
    200: MetricDto;
};

export type GetCompletionErrorRateResponse = GetCompletionErrorRateResponses[keyof GetCompletionErrorRateResponses];

export type GetCompletionAuditData = {
    body?: never;
    path: {
        /**
         * The ID of the workspace
         */
        workspaceId: string;
        /**
         * The ID of the environment
         */
        environmentId: string;
    };
    query: {
        /**
         * The type of audit to list
         */
        type: CompletionAuditType;
        /**
         * The connection ID to list audits for
         */
        connectionId?: string;
        /**
         * The resource to list audits for
         */
        resource?: string;
        /**
         * The model to list audits for
         */
        model?: string;
        /**
         * The status code to list audits for
         */
        statusCode?: number;
        /**
         * The start date to list audits for
         */
        startDate?: string;
        /**
         * The end date to list audits for
         */
        endDate?: string;
    };
    url: '/v1/completion-audit/{workspaceId}/{environmentId}';
};

export type GetCompletionAuditErrors = {
    /**
     * Server Error
     */
    500: ServiceError;
};

export type GetCompletionAuditError = GetCompletionAuditErrors[keyof GetCompletionAuditErrors];

export type GetCompletionAuditResponses = {
    /**
     * List all completion audits associated with an environment
     */
    200: Array<CompletionAuditEntity>;
};

export type GetCompletionAuditResponse = GetCompletionAuditResponses[keyof GetCompletionAuditResponses];

export type GetCompletionUsageData = {
    body: CompletionUsageQueryDto;
    path: {
        /**
         * The ID of the workspace
         */
        workspaceId: string;
        /**
         * The ID of the environment
         */
        environmentId: string;
    };
    query?: never;
    url: '/v1/completion-usage/{workspaceId}/{environmentId}';
};

export type GetCompletionUsageErrors = {
    /**
     * Server Error
     */
    500: ServiceError;
};

export type GetCompletionUsageError = GetCompletionUsageErrors[keyof GetCompletionUsageErrors];

export type GetCompletionUsageResponses = {
    /**
     * List all completion usage records
     */
    200: Array<CompletionUsageQueryResultDto>;
};

export type GetCompletionUsageResponse = GetCompletionUsageResponses[keyof GetCompletionUsageResponses];

export type GetCompletionBatchData = {
    body?: never;
    path: {
        /**
         * The ID of the workspace
         */
        workspaceId: string;
        /**
         * The ID of the environment
         */
        environmentId: string;
        /**
         * The ID of the batch
         */
        batchId: unknown;
    };
    query?: {
        /**
         * Whether to include users in the response
         */
        includesUsers?: boolean;
        /**
         * Whether to include items in the response
         */
        includesItems?: boolean;
    };
    url: '/v1/completion-batch/{workspaceId}/{environmentId}/{batchId}';
};

export type GetCompletionBatchErrors = {
    /**
     * Server Error
     */
    500: ServiceError;
};

export type GetCompletionBatchError = GetCompletionBatchErrors[keyof GetCompletionBatchErrors];

export type GetCompletionBatchResponses = {
    /**
     * Get a completion batch by its ID
     */
    200: CompletionBatchDto;
};

export type GetCompletionBatchResponse = GetCompletionBatchResponses[keyof GetCompletionBatchResponses];

export type GetCompletionBatchItemData = {
    body?: never;
    path: {
        /**
         * The ID of the workspace
         */
        workspaceId: string;
        /**
         * The ID of the environment
         */
        environmentId: string;
        /**
         * The ID of the batch
         */
        batchId: unknown;
        /**
         * The ID of the batch item
         */
        itemId: unknown;
    };
    query?: never;
    url: '/v1/completion-batch/{workspaceId}/{environmentId}/{batchId}/{itemId}';
};

export type GetCompletionBatchItemErrors = {
    /**
     * Server Error
     */
    500: ServiceError;
};

export type GetCompletionBatchItemError = GetCompletionBatchItemErrors[keyof GetCompletionBatchItemErrors];

export type GetCompletionBatchItemResponses = {
    /**
     * Get a completion batch item by its ID
     */
    200: CompletionBatchItemEntity;
};

export type GetCompletionBatchItemResponse = GetCompletionBatchItemResponses[keyof GetCompletionBatchItemResponses];

export type CreateCompletionBatchData = {
    body?: CreateCompletionBatchDto | CreateCompletionCallbackBatchDto;
    path: {
        /**
         * The ID of the workspace
         */
        workspaceId: string;
        /**
         * The ID of the environment
         */
        environmentId: string;
    };
    query?: never;
    url: '/v1/completion-batch/{workspaceId}/{environmentId}';
};

export type CreateCompletionBatchErrors = {
    /**
     * Server Error
     */
    500: ServiceError;
};

export type CreateCompletionBatchError = CreateCompletionBatchErrors[keyof CreateCompletionBatchErrors];

export type CreateCompletionBatchResponses = {
    /**
     * Create a completion batch
     */
    200: CompletionBatchDto;
};

export type CreateCompletionBatchResponse = CreateCompletionBatchResponses[keyof CreateCompletionBatchResponses];

export type CancelCompletionBatchData = {
    body?: never;
    path: {
        /**
         * The ID of the workspace
         */
        workspaceId: string;
        /**
         * The ID of the environment
         */
        environmentId: string;
        /**
         * The ID of the batch
         */
        batchId: unknown;
    };
    query?: never;
    url: '/v1/completion-batch/{workspaceId}/{environmentId}/{batchId}/cancel';
};

export type CancelCompletionBatchErrors = {
    /**
     * Server Error
     */
    500: ServiceError;
};

export type CancelCompletionBatchError = CancelCompletionBatchErrors[keyof CancelCompletionBatchErrors];

export type CancelCompletionBatchResponses = {
    /**
     * Cancel a completion batch by its ID
     */
    200: {
        [key: string]: unknown;
    };
};

export type CancelCompletionBatchResponse = CancelCompletionBatchResponses[keyof CancelCompletionBatchResponses];

export type GetOauth2AuthorizeData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The client ID
         */
        client_id: string;
        /**
         * The response type (usually "code")
         */
        response_type: string;
        /**
         * The redirect URI
         */
        redirect_uri: string;
        /**
         * The requested scopes (e.g., "openid profile email")
         */
        scope?: string;
        /**
         * Opaque state value to maintain state between the request and callback
         */
        state?: string;
        /**
         * Code challenge for PKCE
         */
        code_challenge?: string;
        /**
         * Code challenge method (usually "S256")
         */
        code_challenge_method?: string;
    };
    url: '/oauth2/authorize';
};

export type PostOauth2TokenData = {
    body?: {
        /**
         * The grant type
         */
        grant_type: 'authorization_code' | 'refresh_token' | 'client_credentials';
        /**
         * Authorization code
         */
        code?: string;
        /**
         * Redirect URI
         */
        redirect_uri?: string;
        /**
         * Client ID
         */
        client_id?: string;
        /**
         * Refresh token
         */
        refresh_token?: string;
        /**
         * PKCE code verifier
         */
        code_verifier?: string;
        /**
         * Client secret (for machine-to-machine)
         */
        client_secret?: string;
    };
    path?: never;
    query?: never;
    url: '/oauth2/token';
};

export type PostOauth2TokenResponses = {
    /**
     * Token response
     */
    200: {
        access_token?: string;
        token_type?: string;
        expires_in?: number;
        refresh_token?: string;
        id_token?: string;
        scope?: string;
    };
};

export type PostOauth2TokenResponse = PostOauth2TokenResponses[keyof PostOauth2TokenResponses];

export type GetOauth2UserinfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/oauth2/userinfo';
};

export type GetOauth2UserinfoResponses = {
    /**
     * User claims
     */
    200: {
        sub?: string;
        email?: string;
        email_verified?: boolean;
        name?: string;
        username?: string;
        picture?: string;
        firstName?: string;
        lastName?: string;
    };
};

export type GetOauth2UserinfoResponse = GetOauth2UserinfoResponses[keyof GetOauth2UserinfoResponses];

export type PostOauth2RevokeData = {
    body?: {
        /**
         * The token to revoke
         */
        token: string;
        /**
         * Hint about the token type
         */
        token_type_hint?: 'access_token' | 'refresh_token';
    };
    path?: never;
    query?: never;
    url: '/oauth2/revoke';
};

export type PostOauth2RevokeResponses = {
    /**
     * Token revoked successfully
     */
    200: unknown;
};

export type GetOauth2WellKnownOpenidConfigurationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/oauth2/.well-known/openid-configuration';
};

export type GetOauth2WellKnownOpenidConfigurationResponses = {
    /**
     * OpenID Connect Discovery document
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetOauth2WellKnownOpenidConfigurationResponse = GetOauth2WellKnownOpenidConfigurationResponses[keyof GetOauth2WellKnownOpenidConfigurationResponses];
