// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  queryOptions,
  type UseMutationOptions,
} from '@tanstack/react-query';

import { client } from '../client.gen';
import {
  assignUsersToRole,
  assignUsersToWorkspace,
  cancelCompletionBatch,
  completion,
  createAiConnection,
  createAiResource,
  createApiKey,
  createCompletionBatch,
  createEnvironment,
  createRole,
  createUser,
  createWorkspace,
  deleteAiConnection,
  deleteAiResource,
  deleteApiKey,
  deleteEnvironment,
  deletePoolDefinition,
  deleteRole,
  deleteUser,
  deleteWorkspace,
  getAiConnectionById,
  getAiConnections,
  getAiProviders,
  getAiResourceById,
  getAiResources,
  getApiKeyById,
  getApiKeys,
  getCompletionAudit,
  getCompletionBatch,
  getCompletionBatchItem,
  getCompletionErrorRate,
  getCompletionUsage,
  getEnvironmentById,
  getEnvironments,
  getOauth2Authorize,
  getOauth2Userinfo,
  getOauth2WellKnownOpenidConfiguration,
  getPermissions,
  getPoolDefinition,
  getRoleById,
  getRoleMembers,
  getRoles,
  getUserById,
  getUsers,
  getWorkspaceById,
  getWorkspaceMembers,
  getWorkspaces,
  healthcheckControllerHealthcheck,
  oidcInteractionControllerConsent,
  oidcInteractionControllerFederatedCallback,
  oidcInteractionControllerFederatedInteraction,
  oidcInteractionControllerLogin,
  oidcInteractionControllerShowChangePasswordInteraction,
  oidcInteractionControllerShowInteraction,
  oidcInteractionControllerSubmitChangePassword,
  type Options,
  postOauth2Revoke,
  postOauth2Token,
  unassignUsersFromRole,
  unassignUsersFromWorkspace,
  updateAiConnection,
  updateAiResource,
  updateApiKey,
  updateEnvironment,
  updateMemberRole,
  updatePoolDefinition,
  updateRole,
  updateUser,
  updateWorkspace,
} from '../sdk.gen';
import type {
  AssignUsersToRoleData,
  AssignUsersToRoleError,
  AssignUsersToWorkspaceData,
  AssignUsersToWorkspaceError,
  CancelCompletionBatchData,
  CancelCompletionBatchError,
  CancelCompletionBatchResponse,
  CompletionData,
  CreateAiConnectionData,
  CreateAiConnectionError,
  CreateAiConnectionResponse,
  CreateAiResourceData,
  CreateAiResourceError,
  CreateAiResourceResponse,
  CreateApiKeyData,
  CreateApiKeyError,
  CreateApiKeyResponse,
  CreateCompletionBatchData,
  CreateCompletionBatchError,
  CreateCompletionBatchResponse,
  CreateEnvironmentData,
  CreateEnvironmentError,
  CreateEnvironmentResponse,
  CreateRoleData,
  CreateRoleError,
  CreateRoleResponse,
  CreateUserData,
  CreateUserError,
  CreateUserResponse,
  CreateWorkspaceData,
  CreateWorkspaceError,
  CreateWorkspaceResponse,
  DeleteAiConnectionData,
  DeleteAiConnectionError,
  DeleteAiResourceData,
  DeleteAiResourceError,
  DeleteApiKeyData,
  DeleteApiKeyError,
  DeleteEnvironmentData,
  DeleteEnvironmentError,
  DeletePoolDefinitionData,
  DeletePoolDefinitionError,
  DeleteRoleData,
  DeleteRoleError,
  DeleteUserData,
  DeleteUserError,
  DeleteWorkspaceData,
  DeleteWorkspaceError,
  GetAiConnectionByIdData,
  GetAiConnectionByIdError,
  GetAiConnectionByIdResponse,
  GetAiConnectionsData,
  GetAiConnectionsError,
  GetAiConnectionsResponse,
  GetAiProvidersData,
  GetAiProvidersError,
  GetAiProvidersResponse,
  GetAiResourceByIdData,
  GetAiResourceByIdError,
  GetAiResourceByIdResponse,
  GetAiResourcesData,
  GetAiResourcesError,
  GetAiResourcesResponse,
  GetApiKeyByIdData,
  GetApiKeyByIdError,
  GetApiKeyByIdResponse,
  GetApiKeysData,
  GetApiKeysError,
  GetApiKeysResponse,
  GetCompletionAuditData,
  GetCompletionAuditError,
  GetCompletionAuditResponse,
  GetCompletionBatchData,
  GetCompletionBatchError,
  GetCompletionBatchItemData,
  GetCompletionBatchItemError,
  GetCompletionBatchItemResponse,
  GetCompletionBatchResponse,
  GetCompletionErrorRateData,
  GetCompletionErrorRateError,
  GetCompletionErrorRateResponse,
  GetCompletionUsageData,
  GetCompletionUsageError,
  GetCompletionUsageResponse,
  GetEnvironmentByIdData,
  GetEnvironmentByIdError,
  GetEnvironmentByIdResponse,
  GetEnvironmentsData,
  GetEnvironmentsError,
  GetEnvironmentsResponse,
  GetOauth2AuthorizeData,
  GetOauth2UserinfoData,
  GetOauth2UserinfoResponse,
  GetOauth2WellKnownOpenidConfigurationData,
  GetOauth2WellKnownOpenidConfigurationResponse,
  GetPermissionsData,
  GetPermissionsError,
  GetPermissionsResponse,
  GetPoolDefinitionData,
  GetPoolDefinitionError,
  GetPoolDefinitionResponse,
  GetRoleByIdData,
  GetRoleByIdError,
  GetRoleByIdResponse,
  GetRoleMembersData,
  GetRoleMembersError,
  GetRoleMembersResponse,
  GetRolesData,
  GetRolesError,
  GetRolesResponse,
  GetUserByIdData,
  GetUserByIdError,
  GetUserByIdResponse,
  GetUsersData,
  GetUsersError,
  GetUsersResponse,
  GetWorkspaceByIdData,
  GetWorkspaceByIdError,
  GetWorkspaceByIdResponse,
  GetWorkspaceMembersData,
  GetWorkspaceMembersError,
  GetWorkspaceMembersResponse,
  GetWorkspacesData,
  GetWorkspacesError,
  GetWorkspacesResponse,
  HealthcheckControllerHealthcheckData,
  HealthcheckControllerHealthcheckResponse,
  OidcInteractionControllerConsentData,
  OidcInteractionControllerFederatedCallbackData,
  OidcInteractionControllerFederatedInteractionData,
  OidcInteractionControllerLoginData,
  OidcInteractionControllerShowChangePasswordInteractionData,
  OidcInteractionControllerShowInteractionData,
  OidcInteractionControllerSubmitChangePasswordData,
  PostOauth2RevokeData,
  PostOauth2TokenData,
  PostOauth2TokenResponse,
  UnassignUsersFromRoleData,
  UnassignUsersFromRoleError,
  UnassignUsersFromWorkspaceData,
  UnassignUsersFromWorkspaceError,
  UpdateAiConnectionData,
  UpdateAiConnectionError,
  UpdateAiConnectionResponse,
  UpdateAiResourceData,
  UpdateAiResourceError,
  UpdateAiResourceResponse,
  UpdateApiKeyData,
  UpdateApiKeyError,
  UpdateApiKeyResponse,
  UpdateEnvironmentData,
  UpdateEnvironmentError,
  UpdateEnvironmentResponse,
  UpdateMemberRoleData,
  UpdateMemberRoleError,
  UpdatePoolDefinitionData,
  UpdatePoolDefinitionError,
  UpdatePoolDefinitionResponse,
  UpdateRoleData,
  UpdateRoleError,
  UpdateRoleResponse,
  UpdateUserData,
  UpdateUserError,
  UpdateUserResponse,
  UpdateWorkspaceData,
  UpdateWorkspaceError,
  UpdateWorkspaceResponse,
} from '../types.gen';

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  }
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const healthcheckControllerHealthcheckQueryKey = (
  options?: Options<HealthcheckControllerHealthcheckData>
) => createQueryKey('healthcheckControllerHealthcheck', options);

export const healthcheckControllerHealthcheckOptions = (
  options?: Options<HealthcheckControllerHealthcheckData>
) =>
  queryOptions<
    HealthcheckControllerHealthcheckResponse,
    DefaultError,
    HealthcheckControllerHealthcheckResponse,
    ReturnType<typeof healthcheckControllerHealthcheckQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await healthcheckControllerHealthcheck({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: healthcheckControllerHealthcheckQueryKey(options),
  });

export const getUsersQueryKey = (options?: Options<GetUsersData>) =>
  createQueryKey('getUsers', options);

/**
 * List all users
 *
 * Returns a list of all users.
 */
export const getUsersOptions = (options?: Options<GetUsersData>) =>
  queryOptions<
    GetUsersResponse,
    GetUsersError,
    GetUsersResponse,
    ReturnType<typeof getUsersQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUsers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getUsersQueryKey(options),
  });

/**
 * Create a new user
 *
 * Creates a new user.
 */
export const createUserMutation = (
  options?: Partial<Options<CreateUserData>>
): UseMutationOptions<
  CreateUserResponse,
  CreateUserError,
  Options<CreateUserData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateUserResponse,
    CreateUserError,
    Options<CreateUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete a user
 *
 * Deletes a user by its ID.
 */
export const deleteUserMutation = (
  options?: Partial<Options<DeleteUserData>>
): UseMutationOptions<unknown, DeleteUserError, Options<DeleteUserData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DeleteUserError,
    Options<DeleteUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getUserByIdQueryKey = (options: Options<GetUserByIdData>) =>
  createQueryKey('getUserById', options);

/**
 * Get a user by ID
 *
 * Returns a user by ID.
 */
export const getUserByIdOptions = (options: Options<GetUserByIdData>) =>
  queryOptions<
    GetUserByIdResponse,
    GetUserByIdError,
    GetUserByIdResponse,
    ReturnType<typeof getUserByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUserById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getUserByIdQueryKey(options),
  });

/**
 * Update a user
 *
 * Updates a user by its ID.
 */
export const updateUserMutation = (
  options?: Partial<Options<UpdateUserData>>
): UseMutationOptions<
  UpdateUserResponse,
  UpdateUserError,
  Options<UpdateUserData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateUserResponse,
    UpdateUserError,
    Options<UpdateUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getPermissionsQueryKey = (options?: Options<GetPermissionsData>) =>
  createQueryKey('getPermissions', options);

/**
 * List all available actions for each module
 *
 * Returns a list of all available actions for each module.
 */
export const getPermissionsOptions = (options?: Options<GetPermissionsData>) =>
  queryOptions<
    GetPermissionsResponse,
    GetPermissionsError,
    GetPermissionsResponse,
    ReturnType<typeof getPermissionsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPermissions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getPermissionsQueryKey(options),
  });

export const getRolesQueryKey = (options?: Options<GetRolesData>) =>
  createQueryKey('getRoles', options);

/**
 * List all roles
 *
 * Returns a list of all roles.
 */
export const getRolesOptions = (options?: Options<GetRolesData>) =>
  queryOptions<
    GetRolesResponse,
    GetRolesError,
    GetRolesResponse,
    ReturnType<typeof getRolesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRoles({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getRolesQueryKey(options),
  });

/**
 * Create a new role
 *
 * Creates a new role.
 */
export const createRoleMutation = (
  options?: Partial<Options<CreateRoleData>>
): UseMutationOptions<
  CreateRoleResponse,
  CreateRoleError,
  Options<CreateRoleData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateRoleResponse,
    CreateRoleError,
    Options<CreateRoleData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createRole({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete a role
 *
 * Deletes a role by its ID.
 */
export const deleteRoleMutation = (
  options?: Partial<Options<DeleteRoleData>>
): UseMutationOptions<unknown, DeleteRoleError, Options<DeleteRoleData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DeleteRoleError,
    Options<DeleteRoleData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteRole({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getRoleByIdQueryKey = (options: Options<GetRoleByIdData>) =>
  createQueryKey('getRoleById', options);

/**
 * Get a role by ID
 *
 * Returns a role by its ID. Optionally includes user details in the role if `includesUsers` is set to true (default).
 */
export const getRoleByIdOptions = (options: Options<GetRoleByIdData>) =>
  queryOptions<
    GetRoleByIdResponse,
    GetRoleByIdError,
    GetRoleByIdResponse,
    ReturnType<typeof getRoleByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRoleById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getRoleByIdQueryKey(options),
  });

/**
 * Update a role
 *
 * Updates a role by its ID.
 */
export const updateRoleMutation = (
  options?: Partial<Options<UpdateRoleData>>
): UseMutationOptions<
  UpdateRoleResponse,
  UpdateRoleError,
  Options<UpdateRoleData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateRoleResponse,
    UpdateRoleError,
    Options<UpdateRoleData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateRole({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getRoleMembersQueryKey = (options: Options<GetRoleMembersData>) =>
  createQueryKey('getRoleMembers', options);

/**
 * List all members of a role
 *
 * Returns a list of all members of a role.
 */
export const getRoleMembersOptions = (options: Options<GetRoleMembersData>) =>
  queryOptions<
    GetRoleMembersResponse,
    GetRoleMembersError,
    GetRoleMembersResponse,
    ReturnType<typeof getRoleMembersQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRoleMembers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getRoleMembersQueryKey(options),
  });

/**
 * Assign a role to users
 *
 * Assigns a role to users by their IDs.
 */
export const assignUsersToRoleMutation = (
  options?: Partial<Options<AssignUsersToRoleData>>
): UseMutationOptions<
  unknown,
  AssignUsersToRoleError,
  Options<AssignUsersToRoleData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AssignUsersToRoleError,
    Options<AssignUsersToRoleData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await assignUsersToRole({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Unassign users from a role
 *
 * Unassigns users from a role by their IDs.
 */
export const unassignUsersFromRoleMutation = (
  options?: Partial<Options<UnassignUsersFromRoleData>>
): UseMutationOptions<
  unknown,
  UnassignUsersFromRoleError,
  Options<UnassignUsersFromRoleData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    UnassignUsersFromRoleError,
    Options<UnassignUsersFromRoleData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await unassignUsersFromRole({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const oidcInteractionControllerShowInteractionQueryKey = (
  options: Options<OidcInteractionControllerShowInteractionData>
) => createQueryKey('oidcInteractionControllerShowInteraction', options);

export const oidcInteractionControllerShowInteractionOptions = (
  options: Options<OidcInteractionControllerShowInteractionData>
) =>
  queryOptions<
    unknown,
    DefaultError,
    unknown,
    ReturnType<typeof oidcInteractionControllerShowInteractionQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await oidcInteractionControllerShowInteraction({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: oidcInteractionControllerShowInteractionQueryKey(options),
  });

export const oidcInteractionControllerShowChangePasswordInteractionQueryKey = (
  options: Options<OidcInteractionControllerShowChangePasswordInteractionData>
) =>
  createQueryKey(
    'oidcInteractionControllerShowChangePasswordInteraction',
    options
  );

export const oidcInteractionControllerShowChangePasswordInteractionOptions = (
  options: Options<OidcInteractionControllerShowChangePasswordInteractionData>
) =>
  queryOptions<
    unknown,
    DefaultError,
    unknown,
    ReturnType<
      typeof oidcInteractionControllerShowChangePasswordInteractionQueryKey
    >
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } =
        await oidcInteractionControllerShowChangePasswordInteraction({
          ...options,
          ...queryKey[0],
          signal,
          throwOnError: true,
        });
      return data;
    },
    queryKey:
      oidcInteractionControllerShowChangePasswordInteractionQueryKey(options),
  });

export const oidcInteractionControllerSubmitChangePasswordMutation = (
  options?: Partial<Options<OidcInteractionControllerSubmitChangePasswordData>>
): UseMutationOptions<
  unknown,
  DefaultError,
  Options<OidcInteractionControllerSubmitChangePasswordData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DefaultError,
    Options<OidcInteractionControllerSubmitChangePasswordData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await oidcInteractionControllerSubmitChangePassword({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const oidcInteractionControllerLoginMutation = (
  options?: Partial<Options<OidcInteractionControllerLoginData>>
): UseMutationOptions<
  unknown,
  DefaultError,
  Options<OidcInteractionControllerLoginData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DefaultError,
    Options<OidcInteractionControllerLoginData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await oidcInteractionControllerLogin({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const oidcInteractionControllerConsentMutation = (
  options?: Partial<Options<OidcInteractionControllerConsentData>>
): UseMutationOptions<
  unknown,
  DefaultError,
  Options<OidcInteractionControllerConsentData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DefaultError,
    Options<OidcInteractionControllerConsentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await oidcInteractionControllerConsent({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const oidcInteractionControllerFederatedCallbackQueryKey = (
  options?: Options<OidcInteractionControllerFederatedCallbackData>
) => createQueryKey('oidcInteractionControllerFederatedCallback', options);

export const oidcInteractionControllerFederatedCallbackOptions = (
  options?: Options<OidcInteractionControllerFederatedCallbackData>
) =>
  queryOptions<
    unknown,
    DefaultError,
    unknown,
    ReturnType<typeof oidcInteractionControllerFederatedCallbackQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await oidcInteractionControllerFederatedCallback({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: oidcInteractionControllerFederatedCallbackQueryKey(options),
  });

export const oidcInteractionControllerFederatedInteractionQueryKey = (
  options: Options<OidcInteractionControllerFederatedInteractionData>
) => createQueryKey('oidcInteractionControllerFederatedInteraction', options);

export const oidcInteractionControllerFederatedInteractionOptions = (
  options: Options<OidcInteractionControllerFederatedInteractionData>
) =>
  queryOptions<
    unknown,
    DefaultError,
    unknown,
    ReturnType<typeof oidcInteractionControllerFederatedInteractionQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await oidcInteractionControllerFederatedInteraction({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: oidcInteractionControllerFederatedInteractionQueryKey(options),
  });

export const getWorkspacesQueryKey = (options?: Options<GetWorkspacesData>) =>
  createQueryKey('getWorkspaces', options);

/**
 * List all user workspaces
 *
 * Returns a list of all workspaces that the authenticated user is a member of. Optionally includes user details in each workspace if `includesUsers` is set to true (default).
 */
export const getWorkspacesOptions = (options?: Options<GetWorkspacesData>) =>
  queryOptions<
    GetWorkspacesResponse,
    GetWorkspacesError,
    GetWorkspacesResponse,
    ReturnType<typeof getWorkspacesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWorkspaces({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getWorkspacesQueryKey(options),
  });

/**
 * Create a new workspace
 *
 * Creates a new workspace. The authenticated user is automatically added as the owner of the workspace.
 */
export const createWorkspaceMutation = (
  options?: Partial<Options<CreateWorkspaceData>>
): UseMutationOptions<
  CreateWorkspaceResponse,
  CreateWorkspaceError,
  Options<CreateWorkspaceData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateWorkspaceResponse,
    CreateWorkspaceError,
    Options<CreateWorkspaceData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createWorkspace({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete a workspace
 *
 * Deletes a workspace by its ID. The authenticated user must be a member of the workspace and have the owner role.
 */
export const deleteWorkspaceMutation = (
  options?: Partial<Options<DeleteWorkspaceData>>
): UseMutationOptions<
  unknown,
  DeleteWorkspaceError,
  Options<DeleteWorkspaceData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DeleteWorkspaceError,
    Options<DeleteWorkspaceData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteWorkspace({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getWorkspaceByIdQueryKey = (
  options: Options<GetWorkspaceByIdData>
) => createQueryKey('getWorkspaceById', options);

/**
 * Get a workspace by ID
 *
 * Returns a workspace by its ID. Optionally includes user details in the workspace if `includesUsers` is set to true (default).
 */
export const getWorkspaceByIdOptions = (
  options: Options<GetWorkspaceByIdData>
) =>
  queryOptions<
    GetWorkspaceByIdResponse,
    GetWorkspaceByIdError,
    GetWorkspaceByIdResponse,
    ReturnType<typeof getWorkspaceByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWorkspaceById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getWorkspaceByIdQueryKey(options),
  });

/**
 * Update a workspace
 *
 * Updates a workspace by its ID. The authenticated user must be a member of the workspace and have the owner role.
 */
export const updateWorkspaceMutation = (
  options?: Partial<Options<UpdateWorkspaceData>>
): UseMutationOptions<
  UpdateWorkspaceResponse,
  UpdateWorkspaceError,
  Options<UpdateWorkspaceData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateWorkspaceResponse,
    UpdateWorkspaceError,
    Options<UpdateWorkspaceData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateWorkspace({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getWorkspaceMembersQueryKey = (
  options: Options<GetWorkspaceMembersData>
) => createQueryKey('getWorkspaceMembers', options);

/**
 * Get the members of a workspace
 *
 * Returns the members of a workspace.
 */
export const getWorkspaceMembersOptions = (
  options: Options<GetWorkspaceMembersData>
) =>
  queryOptions<
    GetWorkspaceMembersResponse,
    GetWorkspaceMembersError,
    GetWorkspaceMembersResponse,
    ReturnType<typeof getWorkspaceMembersQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWorkspaceMembers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getWorkspaceMembersQueryKey(options),
  });

/**
 * Update the role of a member of a workspace
 *
 * Updates the role of a member of a workspace by their ID.
 */
export const updateMemberRoleMutation = (
  options?: Partial<Options<UpdateMemberRoleData>>
): UseMutationOptions<
  unknown,
  UpdateMemberRoleError,
  Options<UpdateMemberRoleData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    UpdateMemberRoleError,
    Options<UpdateMemberRoleData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateMemberRole({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Assign users to a workspace
 *
 * Assigns users to a workspace by their IDs.
 */
export const assignUsersToWorkspaceMutation = (
  options?: Partial<Options<AssignUsersToWorkspaceData>>
): UseMutationOptions<
  unknown,
  AssignUsersToWorkspaceError,
  Options<AssignUsersToWorkspaceData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AssignUsersToWorkspaceError,
    Options<AssignUsersToWorkspaceData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await assignUsersToWorkspace({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Unassign users from a workspace
 *
 * Unassigns users from a workspace by their IDs.
 */
export const unassignUsersFromWorkspaceMutation = (
  options?: Partial<Options<UnassignUsersFromWorkspaceData>>
): UseMutationOptions<
  unknown,
  UnassignUsersFromWorkspaceError,
  Options<UnassignUsersFromWorkspaceData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    UnassignUsersFromWorkspaceError,
    Options<UnassignUsersFromWorkspaceData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await unassignUsersFromWorkspace({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getEnvironmentsQueryKey = (
  options: Options<GetEnvironmentsData>
) => createQueryKey('getEnvironments', options);

/**
 * List all user environments
 *
 * Returns a list of all environments that the authenticated user is a member of. Optionally includes user details in each environment if `includesUsers` is set to true (default).
 */
export const getEnvironmentsOptions = (options: Options<GetEnvironmentsData>) =>
  queryOptions<
    GetEnvironmentsResponse,
    GetEnvironmentsError,
    GetEnvironmentsResponse,
    ReturnType<typeof getEnvironmentsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEnvironments({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEnvironmentsQueryKey(options),
  });

/**
 * Create a new environment
 *
 * Creates a new environment. You must be a member of the workspace to create an environment.
 */
export const createEnvironmentMutation = (
  options?: Partial<Options<CreateEnvironmentData>>
): UseMutationOptions<
  CreateEnvironmentResponse,
  CreateEnvironmentError,
  Options<CreateEnvironmentData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateEnvironmentResponse,
    CreateEnvironmentError,
    Options<CreateEnvironmentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createEnvironment({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete an environment
 *
 * Deletes an environment by its ID. You must be a member of the workspace to delete an environment.
 */
export const deleteEnvironmentMutation = (
  options?: Partial<Options<DeleteEnvironmentData>>
): UseMutationOptions<
  unknown,
  DeleteEnvironmentError,
  Options<DeleteEnvironmentData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DeleteEnvironmentError,
    Options<DeleteEnvironmentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteEnvironment({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getEnvironmentByIdQueryKey = (
  options: Options<GetEnvironmentByIdData>
) => createQueryKey('getEnvironmentById', options);

/**
 * Get an environment by ID
 *
 * Returns an environment by its ID. Optionally includes user details in the environment if `includesUsers` is set to true (default).
 */
export const getEnvironmentByIdOptions = (
  options: Options<GetEnvironmentByIdData>
) =>
  queryOptions<
    GetEnvironmentByIdResponse,
    GetEnvironmentByIdError,
    GetEnvironmentByIdResponse,
    ReturnType<typeof getEnvironmentByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEnvironmentById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEnvironmentByIdQueryKey(options),
  });

/**
 * Update an environment
 *
 * Updates an environment by its ID. You must be a member of the workspace to update an environment.
 */
export const updateEnvironmentMutation = (
  options?: Partial<Options<UpdateEnvironmentData>>
): UseMutationOptions<
  UpdateEnvironmentResponse,
  UpdateEnvironmentError,
  Options<UpdateEnvironmentData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateEnvironmentResponse,
    UpdateEnvironmentError,
    Options<UpdateEnvironmentData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateEnvironment({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getAiConnectionsQueryKey = (
  options: Options<GetAiConnectionsData>
) => createQueryKey('getAiConnections', options);

/**
 * List all AI connections associated with an environment
 *
 * Returns a list of all AI connections associated with an environment. Optionally includes user details in each AI connection if `includesUsers` is set to true (default).
 */
export const getAiConnectionsOptions = (
  options: Options<GetAiConnectionsData>
) =>
  queryOptions<
    GetAiConnectionsResponse,
    GetAiConnectionsError,
    GetAiConnectionsResponse,
    ReturnType<typeof getAiConnectionsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAiConnections({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAiConnectionsQueryKey(options),
  });

/**
 * Create a new AI connection
 *
 * Creates a new AI connection. You must be a member of the workspace to create an AI connection.
 */
export const createAiConnectionMutation = (
  options?: Partial<Options<CreateAiConnectionData>>
): UseMutationOptions<
  CreateAiConnectionResponse,
  CreateAiConnectionError,
  Options<CreateAiConnectionData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateAiConnectionResponse,
    CreateAiConnectionError,
    Options<CreateAiConnectionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createAiConnection({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete an AI connection
 *
 * Deletes an AI connection by its ID. You must be a member of the workspace to delete an AI connection.
 */
export const deleteAiConnectionMutation = (
  options?: Partial<Options<DeleteAiConnectionData>>
): UseMutationOptions<
  unknown,
  DeleteAiConnectionError,
  Options<DeleteAiConnectionData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DeleteAiConnectionError,
    Options<DeleteAiConnectionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteAiConnection({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getAiConnectionByIdQueryKey = (
  options: Options<GetAiConnectionByIdData>
) => createQueryKey('getAiConnectionById', options);

/**
 * Get an AI connection by ID
 *
 * Returns an AI connection by its ID. Optionally includes user details in the AI connection if `includesUsers` is set to true (default).
 */
export const getAiConnectionByIdOptions = (
  options: Options<GetAiConnectionByIdData>
) =>
  queryOptions<
    GetAiConnectionByIdResponse,
    GetAiConnectionByIdError,
    GetAiConnectionByIdResponse,
    ReturnType<typeof getAiConnectionByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAiConnectionById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAiConnectionByIdQueryKey(options),
  });

/**
 * Update an AI connection
 *
 * Updates an AI connection by its ID. You must be a member of the workspace to update an AI connection.
 */
export const updateAiConnectionMutation = (
  options?: Partial<Options<UpdateAiConnectionData>>
): UseMutationOptions<
  UpdateAiConnectionResponse,
  UpdateAiConnectionError,
  Options<UpdateAiConnectionData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateAiConnectionResponse,
    UpdateAiConnectionError,
    Options<UpdateAiConnectionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateAiConnection({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getAiProvidersQueryKey = (options?: Options<GetAiProvidersData>) =>
  createQueryKey('getAiProviders', options);

/**
 * List all AI providers
 *
 * Returns a list of all AI providers.
 */
export const getAiProvidersOptions = (options?: Options<GetAiProvidersData>) =>
  queryOptions<
    GetAiProvidersResponse,
    GetAiProvidersError,
    GetAiProvidersResponse,
    ReturnType<typeof getAiProvidersQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAiProviders({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAiProvidersQueryKey(options),
  });

export const getAiResourcesQueryKey = (options: Options<GetAiResourcesData>) =>
  createQueryKey('getAiResources', options);

/**
 * List all AI resources associated with an environment
 *
 * Returns a list of all AI resources associated with an environment. Optionally includes user details in each AI resource if `includesUsers` is set to true (default).
 */
export const getAiResourcesOptions = (options: Options<GetAiResourcesData>) =>
  queryOptions<
    GetAiResourcesResponse,
    GetAiResourcesError,
    GetAiResourcesResponse,
    ReturnType<typeof getAiResourcesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAiResources({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAiResourcesQueryKey(options),
  });

/**
 * Create a new AI resource
 *
 * Creates a new AI resource. You must be a member of the workspace to create an AI resource.
 */
export const createAiResourceMutation = (
  options?: Partial<Options<CreateAiResourceData>>
): UseMutationOptions<
  CreateAiResourceResponse,
  CreateAiResourceError,
  Options<CreateAiResourceData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateAiResourceResponse,
    CreateAiResourceError,
    Options<CreateAiResourceData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createAiResource({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete an AI resource
 *
 * Deletes an AI resource by its ID. You must be a member of the workspace to delete an AI resource.
 */
export const deleteAiResourceMutation = (
  options?: Partial<Options<DeleteAiResourceData>>
): UseMutationOptions<
  unknown,
  DeleteAiResourceError,
  Options<DeleteAiResourceData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DeleteAiResourceError,
    Options<DeleteAiResourceData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteAiResource({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getAiResourceByIdQueryKey = (
  options: Options<GetAiResourceByIdData>
) => createQueryKey('getAiResourceById', options);

/**
 * Get an AI resource by ID
 *
 * Returns an AI resource by its ID. Optionally includes user details in the AI resource if `includesUsers` is set to true (default).
 */
export const getAiResourceByIdOptions = (
  options: Options<GetAiResourceByIdData>
) =>
  queryOptions<
    GetAiResourceByIdResponse,
    GetAiResourceByIdError,
    GetAiResourceByIdResponse,
    ReturnType<typeof getAiResourceByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAiResourceById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAiResourceByIdQueryKey(options),
  });

/**
 * Update an AI resource
 *
 * Updates an AI resource by its ID. You must be a member of the workspace to update an AI resource.
 */
export const updateAiResourceMutation = (
  options?: Partial<Options<UpdateAiResourceData>>
): UseMutationOptions<
  UpdateAiResourceResponse,
  UpdateAiResourceError,
  Options<UpdateAiResourceData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateAiResourceResponse,
    UpdateAiResourceError,
    Options<UpdateAiResourceData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateAiResource({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiKeysQueryKey = (options: Options<GetApiKeysData>) =>
  createQueryKey('getApiKeys', options);

/**
 * List all API keys associated with an environment
 *
 * Returns a list of all API keys associated with an environment. Optionally includes user details in each API key if `includesUsers` is set to true (default).
 */
export const getApiKeysOptions = (options: Options<GetApiKeysData>) =>
  queryOptions<
    GetApiKeysResponse,
    GetApiKeysError,
    GetApiKeysResponse,
    ReturnType<typeof getApiKeysQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiKeys({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiKeysQueryKey(options),
  });

/**
 * Create a new API key
 *
 * Creates a new API key. You must be a member of the workspace to create an API key.
 */
export const createApiKeyMutation = (
  options?: Partial<Options<CreateApiKeyData>>
): UseMutationOptions<
  CreateApiKeyResponse,
  CreateApiKeyError,
  Options<CreateApiKeyData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateApiKeyResponse,
    CreateApiKeyError,
    Options<CreateApiKeyData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createApiKey({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete an API key
 *
 * Deletes an API key by its ID. You must be a member of the workspace to delete an API key.
 */
export const deleteApiKeyMutation = (
  options?: Partial<Options<DeleteApiKeyData>>
): UseMutationOptions<
  unknown,
  DeleteApiKeyError,
  Options<DeleteApiKeyData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DeleteApiKeyError,
    Options<DeleteApiKeyData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiKey({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiKeyByIdQueryKey = (options: Options<GetApiKeyByIdData>) =>
  createQueryKey('getApiKeyById', options);

/**
 * Get an API key by ID
 *
 * Returns an API key by its ID. Optionally includes user details in the API key if `includesUsers` is set to true (default).
 */
export const getApiKeyByIdOptions = (options: Options<GetApiKeyByIdData>) =>
  queryOptions<
    GetApiKeyByIdResponse,
    GetApiKeyByIdError,
    GetApiKeyByIdResponse,
    ReturnType<typeof getApiKeyByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiKeyById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiKeyByIdQueryKey(options),
  });

/**
 * Update an API key
 *
 * Updates an API key by its ID. You must be a member of the workspace to update an API key.
 */
export const updateApiKeyMutation = (
  options?: Partial<Options<UpdateApiKeyData>>
): UseMutationOptions<
  UpdateApiKeyResponse,
  UpdateApiKeyError,
  Options<UpdateApiKeyData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateApiKeyResponse,
    UpdateApiKeyError,
    Options<UpdateApiKeyData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateApiKey({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete a pool definition
 *
 * Deletes a pool definition by its workspace and environment. You must be a member of the workspace to delete a pool definition.
 */
export const deletePoolDefinitionMutation = (
  options?: Partial<Options<DeletePoolDefinitionData>>
): UseMutationOptions<
  unknown,
  DeletePoolDefinitionError,
  Options<DeletePoolDefinitionData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DeletePoolDefinitionError,
    Options<DeletePoolDefinitionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deletePoolDefinition({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getPoolDefinitionQueryKey = (
  options: Options<GetPoolDefinitionData>
) => createQueryKey('getPoolDefinition', options);

/**
 * Get a pool definition by workspace and environment
 *
 * Returns a pool definition by its workspace and environment. Optionally includes user details in the pool definition if `includesUsers` is set to true (default).
 */
export const getPoolDefinitionOptions = (
  options: Options<GetPoolDefinitionData>
) =>
  queryOptions<
    GetPoolDefinitionResponse,
    GetPoolDefinitionError,
    GetPoolDefinitionResponse,
    ReturnType<typeof getPoolDefinitionQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPoolDefinition({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getPoolDefinitionQueryKey(options),
  });

/**
 * Created/updated a pool definition
 *
 * Created/updated a pool definition. You must be a member of the workspace to create/update a pool definition.
 */
export const updatePoolDefinitionMutation = (
  options?: Partial<Options<UpdatePoolDefinitionData>>
): UseMutationOptions<
  UpdatePoolDefinitionResponse,
  UpdatePoolDefinitionError,
  Options<UpdatePoolDefinitionData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdatePoolDefinitionResponse,
    UpdatePoolDefinitionError,
    Options<UpdatePoolDefinitionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updatePoolDefinition({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * LLM Completion
 *
 * Performs a completion request to the LLM API.
 */
export const completionMutation = (
  options?: Partial<Options<CompletionData>>
): UseMutationOptions<unknown, DefaultError, Options<CompletionData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DefaultError,
    Options<CompletionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await completion({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getCompletionErrorRateQueryKey = (
  options: Options<GetCompletionErrorRateData>
) => createQueryKey('getCompletionErrorRate', options);

/**
 * Get the error rate for an AI resource
 *
 * Returns the error rate for an AI resource in the requested window
 */
export const getCompletionErrorRateOptions = (
  options: Options<GetCompletionErrorRateData>
) =>
  queryOptions<
    GetCompletionErrorRateResponse,
    GetCompletionErrorRateError,
    GetCompletionErrorRateResponse,
    ReturnType<typeof getCompletionErrorRateQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCompletionErrorRate({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getCompletionErrorRateQueryKey(options),
  });

export const getCompletionAuditQueryKey = (
  options: Options<GetCompletionAuditData>
) => createQueryKey('getCompletionAudit', options);

/**
 * List all completion audits associated with an environment
 *
 * Returns a list of all completion audits associated with an environment.
 */
export const getCompletionAuditOptions = (
  options: Options<GetCompletionAuditData>
) =>
  queryOptions<
    GetCompletionAuditResponse,
    GetCompletionAuditError,
    GetCompletionAuditResponse,
    ReturnType<typeof getCompletionAuditQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCompletionAudit({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getCompletionAuditQueryKey(options),
  });

/**
 * Query completion usage records
 *
 * Returns a list of completion usage records based on the query parameters
 */
export const getCompletionUsageMutation = (
  options?: Partial<Options<GetCompletionUsageData>>
): UseMutationOptions<
  GetCompletionUsageResponse,
  GetCompletionUsageError,
  Options<GetCompletionUsageData>
> => {
  const mutationOptions: UseMutationOptions<
    GetCompletionUsageResponse,
    GetCompletionUsageError,
    Options<GetCompletionUsageData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await getCompletionUsage({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getCompletionBatchQueryKey = (
  options: Options<GetCompletionBatchData>
) => createQueryKey('getCompletionBatch', options);

/**
 * Get a completion batch
 *
 * Get a completion batch by its ID
 */
export const getCompletionBatchOptions = (
  options: Options<GetCompletionBatchData>
) =>
  queryOptions<
    GetCompletionBatchResponse,
    GetCompletionBatchError,
    GetCompletionBatchResponse,
    ReturnType<typeof getCompletionBatchQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCompletionBatch({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getCompletionBatchQueryKey(options),
  });

export const getCompletionBatchItemQueryKey = (
  options: Options<GetCompletionBatchItemData>
) => createQueryKey('getCompletionBatchItem', options);

/**
 * Get a completion batch item
 *
 * Get a completion batch item by its ID
 */
export const getCompletionBatchItemOptions = (
  options: Options<GetCompletionBatchItemData>
) =>
  queryOptions<
    GetCompletionBatchItemResponse,
    GetCompletionBatchItemError,
    GetCompletionBatchItemResponse,
    ReturnType<typeof getCompletionBatchItemQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCompletionBatchItem({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getCompletionBatchItemQueryKey(options),
  });

/**
 * Create a completion batch
 *
 * Create a completion batch
 */
export const createCompletionBatchMutation = (
  options?: Partial<Options<CreateCompletionBatchData>>
): UseMutationOptions<
  CreateCompletionBatchResponse,
  CreateCompletionBatchError,
  Options<CreateCompletionBatchData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateCompletionBatchResponse,
    CreateCompletionBatchError,
    Options<CreateCompletionBatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createCompletionBatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Cancel a completion batch
 *
 * Cancel a completion batch by its ID
 */
export const cancelCompletionBatchMutation = (
  options?: Partial<Options<CancelCompletionBatchData>>
): UseMutationOptions<
  CancelCompletionBatchResponse,
  CancelCompletionBatchError,
  Options<CancelCompletionBatchData>
> => {
  const mutationOptions: UseMutationOptions<
    CancelCompletionBatchResponse,
    CancelCompletionBatchError,
    Options<CancelCompletionBatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await cancelCompletionBatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getOauth2AuthorizeQueryKey = (
  options: Options<GetOauth2AuthorizeData>
) => createQueryKey('getOauth2Authorize', options);

/**
 * OIDC Authorization Endpoint
 *
 * The authorization endpoint initiates the OAuth2/OpenID Connect flow
 */
export const getOauth2AuthorizeOptions = (
  options: Options<GetOauth2AuthorizeData>
) =>
  queryOptions<
    unknown,
    DefaultError,
    unknown,
    ReturnType<typeof getOauth2AuthorizeQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getOauth2Authorize({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getOauth2AuthorizeQueryKey(options),
  });

/**
 * OIDC Token Endpoint
 *
 * Exchanges authorization codes for access tokens
 */
export const postOauth2TokenMutation = (
  options?: Partial<Options<PostOauth2TokenData>>
): UseMutationOptions<
  PostOauth2TokenResponse,
  DefaultError,
  Options<PostOauth2TokenData>
> => {
  const mutationOptions: UseMutationOptions<
    PostOauth2TokenResponse,
    DefaultError,
    Options<PostOauth2TokenData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postOauth2Token({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getOauth2UserinfoQueryKey = (
  options?: Options<GetOauth2UserinfoData>
) => createQueryKey('getOauth2Userinfo', options);

/**
 * Returns claims about the authenticated end-user
 */
export const getOauth2UserinfoOptions = (
  options?: Options<GetOauth2UserinfoData>
) =>
  queryOptions<
    GetOauth2UserinfoResponse,
    DefaultError,
    GetOauth2UserinfoResponse,
    ReturnType<typeof getOauth2UserinfoQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getOauth2Userinfo({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getOauth2UserinfoQueryKey(options),
  });

/**
 * Token Revocation Endpoint
 *
 * Revokes access or refresh tokens
 */
export const postOauth2RevokeMutation = (
  options?: Partial<Options<PostOauth2RevokeData>>
): UseMutationOptions<unknown, DefaultError, Options<PostOauth2RevokeData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DefaultError,
    Options<PostOauth2RevokeData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postOauth2Revoke({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getOauth2WellKnownOpenidConfigurationQueryKey = (
  options?: Options<GetOauth2WellKnownOpenidConfigurationData>
) => createQueryKey('getOauth2WellKnownOpenidConfiguration', options);

/**
 * OpenID Connect Discovery
 *
 * Returns the OpenID Connect configuration document
 */
export const getOauth2WellKnownOpenidConfigurationOptions = (
  options?: Options<GetOauth2WellKnownOpenidConfigurationData>
) =>
  queryOptions<
    GetOauth2WellKnownOpenidConfigurationResponse,
    DefaultError,
    GetOauth2WellKnownOpenidConfigurationResponse,
    ReturnType<typeof getOauth2WellKnownOpenidConfigurationQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getOauth2WellKnownOpenidConfiguration({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getOauth2WellKnownOpenidConfigurationQueryKey(options),
  });
